/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";

import type {
  HTTPValidationError,
  ListReservationsApiReservationsGetParams,
  ReservationCreate,
  ReservationResponse,
  ReservationUpdate,
} from "../../model";

import { customInstance } from "../../mutator/custom-instance";
import type { ErrorType, BodyType } from "../../mutator/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * List reservations with optional filters.

Security: business_id is required to prevent cross-tenant data access.
 * @summary List Reservations
 */
export const listReservationsApiReservationsGet = (
  params: ListReservationsApiReservationsGetParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ReservationResponse[]>(
    { url: `/api/reservations`, method: "GET", params, signal },
    options,
  );
};

export const getListReservationsApiReservationsGetQueryKey = (
  params?: ListReservationsApiReservationsGetParams,
) => {
  return [`/api/reservations`, ...(params ? [params] : [])] as const;
};

export const getListReservationsApiReservationsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof listReservationsApiReservationsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListReservationsApiReservationsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listReservationsApiReservationsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getListReservationsApiReservationsGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listReservationsApiReservationsGet>>
  > = ({ signal }) =>
    listReservationsApiReservationsGet(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listReservationsApiReservationsGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListReservationsApiReservationsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof listReservationsApiReservationsGet>>
>;
export type ListReservationsApiReservationsGetQueryError =
  ErrorType<HTTPValidationError>;

export function useListReservationsApiReservationsGet<
  TData = Awaited<ReturnType<typeof listReservationsApiReservationsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListReservationsApiReservationsGetParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listReservationsApiReservationsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listReservationsApiReservationsGet>>,
          TError,
          Awaited<ReturnType<typeof listReservationsApiReservationsGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListReservationsApiReservationsGet<
  TData = Awaited<ReturnType<typeof listReservationsApiReservationsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListReservationsApiReservationsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listReservationsApiReservationsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listReservationsApiReservationsGet>>,
          TError,
          Awaited<ReturnType<typeof listReservationsApiReservationsGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListReservationsApiReservationsGet<
  TData = Awaited<ReturnType<typeof listReservationsApiReservationsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListReservationsApiReservationsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listReservationsApiReservationsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List Reservations
 */

export function useListReservationsApiReservationsGet<
  TData = Awaited<ReturnType<typeof listReservationsApiReservationsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListReservationsApiReservationsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listReservationsApiReservationsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListReservationsApiReservationsGetQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getListReservationsApiReservationsGetSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof listReservationsApiReservationsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListReservationsApiReservationsGetParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listReservationsApiReservationsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getListReservationsApiReservationsGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listReservationsApiReservationsGet>>
  > = ({ signal }) =>
    listReservationsApiReservationsGet(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof listReservationsApiReservationsGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListReservationsApiReservationsGetSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof listReservationsApiReservationsGet>>
>;
export type ListReservationsApiReservationsGetSuspenseQueryError =
  ErrorType<HTTPValidationError>;

export function useListReservationsApiReservationsGetSuspense<
  TData = Awaited<ReturnType<typeof listReservationsApiReservationsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListReservationsApiReservationsGetParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listReservationsApiReservationsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListReservationsApiReservationsGetSuspense<
  TData = Awaited<ReturnType<typeof listReservationsApiReservationsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListReservationsApiReservationsGetParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listReservationsApiReservationsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListReservationsApiReservationsGetSuspense<
  TData = Awaited<ReturnType<typeof listReservationsApiReservationsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListReservationsApiReservationsGetParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listReservationsApiReservationsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List Reservations
 */

export function useListReservationsApiReservationsGetSuspense<
  TData = Awaited<ReturnType<typeof listReservationsApiReservationsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListReservationsApiReservationsGetParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listReservationsApiReservationsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getListReservationsApiReservationsGetSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Create a new reservation.
 * @summary Create Reservation
 */
export const createReservationApiReservationsPost = (
  reservationCreate: BodyType<ReservationCreate>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ReservationResponse>(
    {
      url: `/api/reservations`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: reservationCreate,
      signal,
    },
    options,
  );
};

export const getCreateReservationApiReservationsPostMutationOptions = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createReservationApiReservationsPost>>,
    TError,
    { data: BodyType<ReservationCreate> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createReservationApiReservationsPost>>,
  TError,
  { data: BodyType<ReservationCreate> },
  TContext
> => {
  const mutationKey = ["createReservationApiReservationsPost"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createReservationApiReservationsPost>>,
    { data: BodyType<ReservationCreate> }
  > = (props) => {
    const { data } = props ?? {};

    return createReservationApiReservationsPost(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateReservationApiReservationsPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof createReservationApiReservationsPost>>
>;
export type CreateReservationApiReservationsPostMutationBody =
  BodyType<ReservationCreate>;
export type CreateReservationApiReservationsPostMutationError =
  ErrorType<HTTPValidationError>;

/**
 * @summary Create Reservation
 */
export const useCreateReservationApiReservationsPost = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createReservationApiReservationsPost>>,
      TError,
      { data: BodyType<ReservationCreate> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createReservationApiReservationsPost>>,
  TError,
  { data: BodyType<ReservationCreate> },
  TContext
> => {
  const mutationOptions =
    getCreateReservationApiReservationsPostMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Get a reservation by ID.
 * @summary Get Reservation
 */
export const getReservationApiReservationsReservationIdGet = (
  reservationId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ReservationResponse>(
    { url: `/api/reservations/${reservationId}`, method: "GET", signal },
    options,
  );
};

export const getGetReservationApiReservationsReservationIdGetQueryKey = (
  reservationId?: string,
) => {
  return [`/api/reservations/${reservationId}`] as const;
};

export const getGetReservationApiReservationsReservationIdGetQueryOptions = <
  TData = Awaited<
    ReturnType<typeof getReservationApiReservationsReservationIdGet>
  >,
  TError = ErrorType<HTTPValidationError>,
>(
  reservationId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getReservationApiReservationsReservationIdGet>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetReservationApiReservationsReservationIdGetQueryKey(reservationId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getReservationApiReservationsReservationIdGet>>
  > = ({ signal }) =>
    getReservationApiReservationsReservationIdGet(
      reservationId,
      requestOptions,
      signal,
    );

  return {
    queryKey,
    queryFn,
    enabled: !!reservationId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getReservationApiReservationsReservationIdGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetReservationApiReservationsReservationIdGetQueryResult =
  NonNullable<
    Awaited<ReturnType<typeof getReservationApiReservationsReservationIdGet>>
  >;
export type GetReservationApiReservationsReservationIdGetQueryError =
  ErrorType<HTTPValidationError>;

export function useGetReservationApiReservationsReservationIdGet<
  TData = Awaited<
    ReturnType<typeof getReservationApiReservationsReservationIdGet>
  >,
  TError = ErrorType<HTTPValidationError>,
>(
  reservationId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getReservationApiReservationsReservationIdGet>
        >,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof getReservationApiReservationsReservationIdGet>
          >,
          TError,
          Awaited<
            ReturnType<typeof getReservationApiReservationsReservationIdGet>
          >
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReservationApiReservationsReservationIdGet<
  TData = Awaited<
    ReturnType<typeof getReservationApiReservationsReservationIdGet>
  >,
  TError = ErrorType<HTTPValidationError>,
>(
  reservationId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getReservationApiReservationsReservationIdGet>
        >,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof getReservationApiReservationsReservationIdGet>
          >,
          TError,
          Awaited<
            ReturnType<typeof getReservationApiReservationsReservationIdGet>
          >
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReservationApiReservationsReservationIdGet<
  TData = Awaited<
    ReturnType<typeof getReservationApiReservationsReservationIdGet>
  >,
  TError = ErrorType<HTTPValidationError>,
>(
  reservationId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getReservationApiReservationsReservationIdGet>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Reservation
 */

export function useGetReservationApiReservationsReservationIdGet<
  TData = Awaited<
    ReturnType<typeof getReservationApiReservationsReservationIdGet>
  >,
  TError = ErrorType<HTTPValidationError>,
>(
  reservationId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getReservationApiReservationsReservationIdGet>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getGetReservationApiReservationsReservationIdGetQueryOptions(
      reservationId,
      options,
    );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetReservationApiReservationsReservationIdGetSuspenseQueryOptions =
  <
    TData = Awaited<
      ReturnType<typeof getReservationApiReservationsReservationIdGet>
    >,
    TError = ErrorType<HTTPValidationError>,
  >(
    reservationId: string,
    options?: {
      query?: Partial<
        UseSuspenseQueryOptions<
          Awaited<
            ReturnType<typeof getReservationApiReservationsReservationIdGet>
          >,
          TError,
          TData
        >
      >;
      request?: SecondParameter<typeof customInstance>;
    },
  ) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
      queryOptions?.queryKey ??
      getGetReservationApiReservationsReservationIdGetQueryKey(reservationId);

    const queryFn: QueryFunction<
      Awaited<ReturnType<typeof getReservationApiReservationsReservationIdGet>>
    > = ({ signal }) =>
      getReservationApiReservationsReservationIdGet(
        reservationId,
        requestOptions,
        signal,
      );

    return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getReservationApiReservationsReservationIdGet>>,
      TError,
      TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
  };

export type GetReservationApiReservationsReservationIdGetSuspenseQueryResult =
  NonNullable<
    Awaited<ReturnType<typeof getReservationApiReservationsReservationIdGet>>
  >;
export type GetReservationApiReservationsReservationIdGetSuspenseQueryError =
  ErrorType<HTTPValidationError>;

export function useGetReservationApiReservationsReservationIdGetSuspense<
  TData = Awaited<
    ReturnType<typeof getReservationApiReservationsReservationIdGet>
  >,
  TError = ErrorType<HTTPValidationError>,
>(
  reservationId: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<
          ReturnType<typeof getReservationApiReservationsReservationIdGet>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReservationApiReservationsReservationIdGetSuspense<
  TData = Awaited<
    ReturnType<typeof getReservationApiReservationsReservationIdGet>
  >,
  TError = ErrorType<HTTPValidationError>,
>(
  reservationId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<
          ReturnType<typeof getReservationApiReservationsReservationIdGet>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReservationApiReservationsReservationIdGetSuspense<
  TData = Awaited<
    ReturnType<typeof getReservationApiReservationsReservationIdGet>
  >,
  TError = ErrorType<HTTPValidationError>,
>(
  reservationId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<
          ReturnType<typeof getReservationApiReservationsReservationIdGet>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Reservation
 */

export function useGetReservationApiReservationsReservationIdGetSuspense<
  TData = Awaited<
    ReturnType<typeof getReservationApiReservationsReservationIdGet>
  >,
  TError = ErrorType<HTTPValidationError>,
>(
  reservationId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<
          ReturnType<typeof getReservationApiReservationsReservationIdGet>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getGetReservationApiReservationsReservationIdGetSuspenseQueryOptions(
      reservationId,
      options,
    );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Update a reservation (partial update).
 * @summary Update Reservation
 */
export const updateReservationApiReservationsReservationIdPatch = (
  reservationId: string,
  reservationUpdate: BodyType<ReservationUpdate>,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<ReservationResponse>(
    {
      url: `/api/reservations/${reservationId}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: reservationUpdate,
    },
    options,
  );
};

export const getUpdateReservationApiReservationsReservationIdPatchMutationOptions =
  <TError = ErrorType<HTTPValidationError>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<typeof updateReservationApiReservationsReservationIdPatch>
      >,
      TError,
      { reservationId: string; data: BodyType<ReservationUpdate> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  }): UseMutationOptions<
    Awaited<
      ReturnType<typeof updateReservationApiReservationsReservationIdPatch>
    >,
    TError,
    { reservationId: string; data: BodyType<ReservationUpdate> },
    TContext
  > => {
    const mutationKey = ["updateReservationApiReservationsReservationIdPatch"];
    const { mutation: mutationOptions, request: requestOptions } = options
      ? options.mutation &&
        "mutationKey" in options.mutation &&
        options.mutation.mutationKey
        ? options
        : { ...options, mutation: { ...options.mutation, mutationKey } }
      : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
      Awaited<
        ReturnType<typeof updateReservationApiReservationsReservationIdPatch>
      >,
      { reservationId: string; data: BodyType<ReservationUpdate> }
    > = (props) => {
      const { reservationId, data } = props ?? {};

      return updateReservationApiReservationsReservationIdPatch(
        reservationId,
        data,
        requestOptions,
      );
    };

    return { mutationFn, ...mutationOptions };
  };

export type UpdateReservationApiReservationsReservationIdPatchMutationResult =
  NonNullable<
    Awaited<
      ReturnType<typeof updateReservationApiReservationsReservationIdPatch>
    >
  >;
export type UpdateReservationApiReservationsReservationIdPatchMutationBody =
  BodyType<ReservationUpdate>;
export type UpdateReservationApiReservationsReservationIdPatchMutationError =
  ErrorType<HTTPValidationError>;

/**
 * @summary Update Reservation
 */
export const useUpdateReservationApiReservationsReservationIdPatch = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<typeof updateReservationApiReservationsReservationIdPatch>
      >,
      TError,
      { reservationId: string; data: BodyType<ReservationUpdate> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<
    ReturnType<typeof updateReservationApiReservationsReservationIdPatch>
  >,
  TError,
  { reservationId: string; data: BodyType<ReservationUpdate> },
  TContext
> => {
  const mutationOptions =
    getUpdateReservationApiReservationsReservationIdPatchMutationOptions(
      options,
    );

  return useMutation(mutationOptions, queryClient);
};
/**
 * Delete a reservation.
 * @summary Delete Reservation
 */
export const deleteReservationApiReservationsReservationIdDelete = (
  reservationId: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    { url: `/api/reservations/${reservationId}`, method: "DELETE" },
    options,
  );
};

export const getDeleteReservationApiReservationsReservationIdDeleteMutationOptions =
  <TError = ErrorType<HTTPValidationError>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<typeof deleteReservationApiReservationsReservationIdDelete>
      >,
      TError,
      { reservationId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  }): UseMutationOptions<
    Awaited<
      ReturnType<typeof deleteReservationApiReservationsReservationIdDelete>
    >,
    TError,
    { reservationId: string },
    TContext
  > => {
    const mutationKey = ["deleteReservationApiReservationsReservationIdDelete"];
    const { mutation: mutationOptions, request: requestOptions } = options
      ? options.mutation &&
        "mutationKey" in options.mutation &&
        options.mutation.mutationKey
        ? options
        : { ...options, mutation: { ...options.mutation, mutationKey } }
      : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
      Awaited<
        ReturnType<typeof deleteReservationApiReservationsReservationIdDelete>
      >,
      { reservationId: string }
    > = (props) => {
      const { reservationId } = props ?? {};

      return deleteReservationApiReservationsReservationIdDelete(
        reservationId,
        requestOptions,
      );
    };

    return { mutationFn, ...mutationOptions };
  };

export type DeleteReservationApiReservationsReservationIdDeleteMutationResult =
  NonNullable<
    Awaited<
      ReturnType<typeof deleteReservationApiReservationsReservationIdDelete>
    >
  >;

export type DeleteReservationApiReservationsReservationIdDeleteMutationError =
  ErrorType<HTTPValidationError>;

/**
 * @summary Delete Reservation
 */
export const useDeleteReservationApiReservationsReservationIdDelete = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<typeof deleteReservationApiReservationsReservationIdDelete>
      >,
      TError,
      { reservationId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<
    ReturnType<typeof deleteReservationApiReservationsReservationIdDelete>
  >,
  TError,
  { reservationId: string },
  TContext
> => {
  const mutationOptions =
    getDeleteReservationApiReservationsReservationIdDeleteMutationOptions(
      options,
    );

  return useMutation(mutationOptions, queryClient);
};
