/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";

import type {
  GetReviewStatsApiReviewsStatsGetParams,
  HTTPValidationError,
  ImprovementSuggestionResponse,
  ListReviewsApiReviewsGetParams,
  ListSuggestionsApiReviewsSuggestionsGetParams,
  ReviewStatsResponse,
  TranscriptReviewResponse,
  TriggerAnalysisRequest,
  TriggerAnalysisResponse,
  UpdateSuggestionRequest,
} from "../../model";

import { customInstance } from "../../mutator/custom-instance";
import type { ErrorType, BodyType } from "../../mutator/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * List transcript reviews for a business.

Security: Requires JWT authentication. business_id must match authorized tenant.
 * @summary List Reviews
 */
export const listReviewsApiReviewsGet = (
  params: ListReviewsApiReviewsGetParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<TranscriptReviewResponse[]>(
    { url: `/api/reviews`, method: "GET", params, signal },
    options,
  );
};

export const getListReviewsApiReviewsGetQueryKey = (
  params?: ListReviewsApiReviewsGetParams,
) => {
  return [`/api/reviews`, ...(params ? [params] : [])] as const;
};

export const getListReviewsApiReviewsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof listReviewsApiReviewsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListReviewsApiReviewsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listReviewsApiReviewsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListReviewsApiReviewsGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listReviewsApiReviewsGet>>
  > = ({ signal }) => listReviewsApiReviewsGet(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listReviewsApiReviewsGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListReviewsApiReviewsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof listReviewsApiReviewsGet>>
>;
export type ListReviewsApiReviewsGetQueryError = ErrorType<HTTPValidationError>;

export function useListReviewsApiReviewsGet<
  TData = Awaited<ReturnType<typeof listReviewsApiReviewsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListReviewsApiReviewsGetParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listReviewsApiReviewsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listReviewsApiReviewsGet>>,
          TError,
          Awaited<ReturnType<typeof listReviewsApiReviewsGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListReviewsApiReviewsGet<
  TData = Awaited<ReturnType<typeof listReviewsApiReviewsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListReviewsApiReviewsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listReviewsApiReviewsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listReviewsApiReviewsGet>>,
          TError,
          Awaited<ReturnType<typeof listReviewsApiReviewsGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListReviewsApiReviewsGet<
  TData = Awaited<ReturnType<typeof listReviewsApiReviewsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListReviewsApiReviewsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listReviewsApiReviewsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List Reviews
 */

export function useListReviewsApiReviewsGet<
  TData = Awaited<ReturnType<typeof listReviewsApiReviewsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListReviewsApiReviewsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listReviewsApiReviewsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListReviewsApiReviewsGetQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getListReviewsApiReviewsGetSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof listReviewsApiReviewsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListReviewsApiReviewsGetParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listReviewsApiReviewsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListReviewsApiReviewsGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listReviewsApiReviewsGet>>
  > = ({ signal }) => listReviewsApiReviewsGet(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof listReviewsApiReviewsGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListReviewsApiReviewsGetSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof listReviewsApiReviewsGet>>
>;
export type ListReviewsApiReviewsGetSuspenseQueryError =
  ErrorType<HTTPValidationError>;

export function useListReviewsApiReviewsGetSuspense<
  TData = Awaited<ReturnType<typeof listReviewsApiReviewsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListReviewsApiReviewsGetParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listReviewsApiReviewsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListReviewsApiReviewsGetSuspense<
  TData = Awaited<ReturnType<typeof listReviewsApiReviewsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListReviewsApiReviewsGetParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listReviewsApiReviewsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListReviewsApiReviewsGetSuspense<
  TData = Awaited<ReturnType<typeof listReviewsApiReviewsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListReviewsApiReviewsGetParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listReviewsApiReviewsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List Reviews
 */

export function useListReviewsApiReviewsGetSuspense<
  TData = Awaited<ReturnType<typeof listReviewsApiReviewsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListReviewsApiReviewsGetParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listReviewsApiReviewsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListReviewsApiReviewsGetSuspenseQueryOptions(
    params,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get statistics about transcript reviews.

Security: Requires JWT authentication. business_id must match authorized tenant.
 * @summary Get Review Stats
 */
export const getReviewStatsApiReviewsStatsGet = (
  params: GetReviewStatsApiReviewsStatsGetParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ReviewStatsResponse>(
    { url: `/api/reviews/stats`, method: "GET", params, signal },
    options,
  );
};

export const getGetReviewStatsApiReviewsStatsGetQueryKey = (
  params?: GetReviewStatsApiReviewsStatsGetParams,
) => {
  return [`/api/reviews/stats`, ...(params ? [params] : [])] as const;
};

export const getGetReviewStatsApiReviewsStatsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getReviewStatsApiReviewsStatsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: GetReviewStatsApiReviewsStatsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReviewStatsApiReviewsStatsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetReviewStatsApiReviewsStatsGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getReviewStatsApiReviewsStatsGet>>
  > = ({ signal }) =>
    getReviewStatsApiReviewsStatsGet(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getReviewStatsApiReviewsStatsGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetReviewStatsApiReviewsStatsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getReviewStatsApiReviewsStatsGet>>
>;
export type GetReviewStatsApiReviewsStatsGetQueryError =
  ErrorType<HTTPValidationError>;

export function useGetReviewStatsApiReviewsStatsGet<
  TData = Awaited<ReturnType<typeof getReviewStatsApiReviewsStatsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: GetReviewStatsApiReviewsStatsGetParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReviewStatsApiReviewsStatsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReviewStatsApiReviewsStatsGet>>,
          TError,
          Awaited<ReturnType<typeof getReviewStatsApiReviewsStatsGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReviewStatsApiReviewsStatsGet<
  TData = Awaited<ReturnType<typeof getReviewStatsApiReviewsStatsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: GetReviewStatsApiReviewsStatsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReviewStatsApiReviewsStatsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReviewStatsApiReviewsStatsGet>>,
          TError,
          Awaited<ReturnType<typeof getReviewStatsApiReviewsStatsGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReviewStatsApiReviewsStatsGet<
  TData = Awaited<ReturnType<typeof getReviewStatsApiReviewsStatsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: GetReviewStatsApiReviewsStatsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReviewStatsApiReviewsStatsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Review Stats
 */

export function useGetReviewStatsApiReviewsStatsGet<
  TData = Awaited<ReturnType<typeof getReviewStatsApiReviewsStatsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: GetReviewStatsApiReviewsStatsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReviewStatsApiReviewsStatsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetReviewStatsApiReviewsStatsGetQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetReviewStatsApiReviewsStatsGetSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getReviewStatsApiReviewsStatsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: GetReviewStatsApiReviewsStatsGetParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getReviewStatsApiReviewsStatsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetReviewStatsApiReviewsStatsGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getReviewStatsApiReviewsStatsGet>>
  > = ({ signal }) =>
    getReviewStatsApiReviewsStatsGet(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getReviewStatsApiReviewsStatsGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetReviewStatsApiReviewsStatsGetSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getReviewStatsApiReviewsStatsGet>>
>;
export type GetReviewStatsApiReviewsStatsGetSuspenseQueryError =
  ErrorType<HTTPValidationError>;

export function useGetReviewStatsApiReviewsStatsGetSuspense<
  TData = Awaited<ReturnType<typeof getReviewStatsApiReviewsStatsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: GetReviewStatsApiReviewsStatsGetParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getReviewStatsApiReviewsStatsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReviewStatsApiReviewsStatsGetSuspense<
  TData = Awaited<ReturnType<typeof getReviewStatsApiReviewsStatsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: GetReviewStatsApiReviewsStatsGetParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getReviewStatsApiReviewsStatsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReviewStatsApiReviewsStatsGetSuspense<
  TData = Awaited<ReturnType<typeof getReviewStatsApiReviewsStatsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: GetReviewStatsApiReviewsStatsGetParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getReviewStatsApiReviewsStatsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Review Stats
 */

export function useGetReviewStatsApiReviewsStatsGetSuspense<
  TData = Awaited<ReturnType<typeof getReviewStatsApiReviewsStatsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: GetReviewStatsApiReviewsStatsGetParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getReviewStatsApiReviewsStatsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetReviewStatsApiReviewsStatsGetSuspenseQueryOptions(
    params,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get a specific transcript review.

Security: Requires JWT authentication. Review must belong to authorized tenant.
 * @summary Get Review
 */
export const getReviewApiReviewsReviewIdGet = (
  reviewId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<TranscriptReviewResponse>(
    { url: `/api/reviews/${reviewId}`, method: "GET", signal },
    options,
  );
};

export const getGetReviewApiReviewsReviewIdGetQueryKey = (
  reviewId?: string,
) => {
  return [`/api/reviews/${reviewId}`] as const;
};

export const getGetReviewApiReviewsReviewIdGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getReviewApiReviewsReviewIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  reviewId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReviewApiReviewsReviewIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetReviewApiReviewsReviewIdGetQueryKey(reviewId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getReviewApiReviewsReviewIdGet>>
  > = ({ signal }) =>
    getReviewApiReviewsReviewIdGet(reviewId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!reviewId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getReviewApiReviewsReviewIdGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetReviewApiReviewsReviewIdGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getReviewApiReviewsReviewIdGet>>
>;
export type GetReviewApiReviewsReviewIdGetQueryError =
  ErrorType<HTTPValidationError>;

export function useGetReviewApiReviewsReviewIdGet<
  TData = Awaited<ReturnType<typeof getReviewApiReviewsReviewIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  reviewId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReviewApiReviewsReviewIdGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReviewApiReviewsReviewIdGet>>,
          TError,
          Awaited<ReturnType<typeof getReviewApiReviewsReviewIdGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReviewApiReviewsReviewIdGet<
  TData = Awaited<ReturnType<typeof getReviewApiReviewsReviewIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  reviewId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReviewApiReviewsReviewIdGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReviewApiReviewsReviewIdGet>>,
          TError,
          Awaited<ReturnType<typeof getReviewApiReviewsReviewIdGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReviewApiReviewsReviewIdGet<
  TData = Awaited<ReturnType<typeof getReviewApiReviewsReviewIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  reviewId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReviewApiReviewsReviewIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Review
 */

export function useGetReviewApiReviewsReviewIdGet<
  TData = Awaited<ReturnType<typeof getReviewApiReviewsReviewIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  reviewId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReviewApiReviewsReviewIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetReviewApiReviewsReviewIdGetQueryOptions(
    reviewId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetReviewApiReviewsReviewIdGetSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getReviewApiReviewsReviewIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  reviewId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getReviewApiReviewsReviewIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetReviewApiReviewsReviewIdGetQueryKey(reviewId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getReviewApiReviewsReviewIdGet>>
  > = ({ signal }) =>
    getReviewApiReviewsReviewIdGet(reviewId, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getReviewApiReviewsReviewIdGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetReviewApiReviewsReviewIdGetSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getReviewApiReviewsReviewIdGet>>
>;
export type GetReviewApiReviewsReviewIdGetSuspenseQueryError =
  ErrorType<HTTPValidationError>;

export function useGetReviewApiReviewsReviewIdGetSuspense<
  TData = Awaited<ReturnType<typeof getReviewApiReviewsReviewIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  reviewId: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getReviewApiReviewsReviewIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReviewApiReviewsReviewIdGetSuspense<
  TData = Awaited<ReturnType<typeof getReviewApiReviewsReviewIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  reviewId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getReviewApiReviewsReviewIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReviewApiReviewsReviewIdGetSuspense<
  TData = Awaited<ReturnType<typeof getReviewApiReviewsReviewIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  reviewId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getReviewApiReviewsReviewIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Review
 */

export function useGetReviewApiReviewsReviewIdGetSuspense<
  TData = Awaited<ReturnType<typeof getReviewApiReviewsReviewIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  reviewId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getReviewApiReviewsReviewIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetReviewApiReviewsReviewIdGetSuspenseQueryOptions(
    reviewId,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Trigger transcript analysis for a specific call.

Queues a background job to analyze the call using AI agents.
Security: Requires JWT authentication. Call must belong to authorized tenant.
 * @summary Trigger Analysis
 */
export const triggerAnalysisApiReviewsAnalyzePost = (
  triggerAnalysisRequest: BodyType<TriggerAnalysisRequest>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<TriggerAnalysisResponse>(
    {
      url: `/api/reviews/analyze`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: triggerAnalysisRequest,
      signal,
    },
    options,
  );
};

export const getTriggerAnalysisApiReviewsAnalyzePostMutationOptions = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof triggerAnalysisApiReviewsAnalyzePost>>,
    TError,
    { data: BodyType<TriggerAnalysisRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof triggerAnalysisApiReviewsAnalyzePost>>,
  TError,
  { data: BodyType<TriggerAnalysisRequest> },
  TContext
> => {
  const mutationKey = ["triggerAnalysisApiReviewsAnalyzePost"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof triggerAnalysisApiReviewsAnalyzePost>>,
    { data: BodyType<TriggerAnalysisRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return triggerAnalysisApiReviewsAnalyzePost(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TriggerAnalysisApiReviewsAnalyzePostMutationResult = NonNullable<
  Awaited<ReturnType<typeof triggerAnalysisApiReviewsAnalyzePost>>
>;
export type TriggerAnalysisApiReviewsAnalyzePostMutationBody =
  BodyType<TriggerAnalysisRequest>;
export type TriggerAnalysisApiReviewsAnalyzePostMutationError =
  ErrorType<HTTPValidationError>;

/**
 * @summary Trigger Analysis
 */
export const useTriggerAnalysisApiReviewsAnalyzePost = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof triggerAnalysisApiReviewsAnalyzePost>>,
      TError,
      { data: BodyType<TriggerAnalysisRequest> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof triggerAnalysisApiReviewsAnalyzePost>>,
  TError,
  { data: BodyType<TriggerAnalysisRequest> },
  TContext
> => {
  const mutationOptions =
    getTriggerAnalysisApiReviewsAnalyzePostMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * List improvement suggestions for a business.

Security: Requires JWT authentication. business_id must match authorized tenant.
 * @summary List Suggestions
 */
export const listSuggestionsApiReviewsSuggestionsGet = (
  params: ListSuggestionsApiReviewsSuggestionsGetParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ImprovementSuggestionResponse[]>(
    { url: `/api/reviews/suggestions`, method: "GET", params, signal },
    options,
  );
};

export const getListSuggestionsApiReviewsSuggestionsGetQueryKey = (
  params?: ListSuggestionsApiReviewsSuggestionsGetParams,
) => {
  return [`/api/reviews/suggestions`, ...(params ? [params] : [])] as const;
};

export const getListSuggestionsApiReviewsSuggestionsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof listSuggestionsApiReviewsSuggestionsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListSuggestionsApiReviewsSuggestionsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listSuggestionsApiReviewsSuggestionsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getListSuggestionsApiReviewsSuggestionsGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listSuggestionsApiReviewsSuggestionsGet>>
  > = ({ signal }) =>
    listSuggestionsApiReviewsSuggestionsGet(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listSuggestionsApiReviewsSuggestionsGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListSuggestionsApiReviewsSuggestionsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof listSuggestionsApiReviewsSuggestionsGet>>
>;
export type ListSuggestionsApiReviewsSuggestionsGetQueryError =
  ErrorType<HTTPValidationError>;

export function useListSuggestionsApiReviewsSuggestionsGet<
  TData = Awaited<ReturnType<typeof listSuggestionsApiReviewsSuggestionsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListSuggestionsApiReviewsSuggestionsGetParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listSuggestionsApiReviewsSuggestionsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSuggestionsApiReviewsSuggestionsGet>>,
          TError,
          Awaited<ReturnType<typeof listSuggestionsApiReviewsSuggestionsGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListSuggestionsApiReviewsSuggestionsGet<
  TData = Awaited<ReturnType<typeof listSuggestionsApiReviewsSuggestionsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListSuggestionsApiReviewsSuggestionsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listSuggestionsApiReviewsSuggestionsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSuggestionsApiReviewsSuggestionsGet>>,
          TError,
          Awaited<ReturnType<typeof listSuggestionsApiReviewsSuggestionsGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListSuggestionsApiReviewsSuggestionsGet<
  TData = Awaited<ReturnType<typeof listSuggestionsApiReviewsSuggestionsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListSuggestionsApiReviewsSuggestionsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listSuggestionsApiReviewsSuggestionsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List Suggestions
 */

export function useListSuggestionsApiReviewsSuggestionsGet<
  TData = Awaited<ReturnType<typeof listSuggestionsApiReviewsSuggestionsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListSuggestionsApiReviewsSuggestionsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listSuggestionsApiReviewsSuggestionsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListSuggestionsApiReviewsSuggestionsGetQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getListSuggestionsApiReviewsSuggestionsGetSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof listSuggestionsApiReviewsSuggestionsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListSuggestionsApiReviewsSuggestionsGetParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listSuggestionsApiReviewsSuggestionsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getListSuggestionsApiReviewsSuggestionsGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listSuggestionsApiReviewsSuggestionsGet>>
  > = ({ signal }) =>
    listSuggestionsApiReviewsSuggestionsGet(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof listSuggestionsApiReviewsSuggestionsGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListSuggestionsApiReviewsSuggestionsGetSuspenseQueryResult =
  NonNullable<
    Awaited<ReturnType<typeof listSuggestionsApiReviewsSuggestionsGet>>
  >;
export type ListSuggestionsApiReviewsSuggestionsGetSuspenseQueryError =
  ErrorType<HTTPValidationError>;

export function useListSuggestionsApiReviewsSuggestionsGetSuspense<
  TData = Awaited<ReturnType<typeof listSuggestionsApiReviewsSuggestionsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListSuggestionsApiReviewsSuggestionsGetParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listSuggestionsApiReviewsSuggestionsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListSuggestionsApiReviewsSuggestionsGetSuspense<
  TData = Awaited<ReturnType<typeof listSuggestionsApiReviewsSuggestionsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListSuggestionsApiReviewsSuggestionsGetParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listSuggestionsApiReviewsSuggestionsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListSuggestionsApiReviewsSuggestionsGetSuspense<
  TData = Awaited<ReturnType<typeof listSuggestionsApiReviewsSuggestionsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListSuggestionsApiReviewsSuggestionsGetParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listSuggestionsApiReviewsSuggestionsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List Suggestions
 */

export function useListSuggestionsApiReviewsSuggestionsGetSuspense<
  TData = Awaited<ReturnType<typeof listSuggestionsApiReviewsSuggestionsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListSuggestionsApiReviewsSuggestionsGetParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listSuggestionsApiReviewsSuggestionsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getListSuggestionsApiReviewsSuggestionsGetSuspenseQueryOptions(
      params,
      options,
    );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Update the status of an improvement suggestion.

Use this to mark suggestions as implemented or rejected.
Security: Requires JWT authentication. Suggestion must belong to authorized tenant.
 * @summary Update Suggestion
 */
export const updateSuggestionApiReviewsSuggestionsSuggestionIdPatch = (
  suggestionId: string,
  updateSuggestionRequest: BodyType<UpdateSuggestionRequest>,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<ImprovementSuggestionResponse>(
    {
      url: `/api/reviews/suggestions/${suggestionId}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateSuggestionRequest,
    },
    options,
  );
};

export const getUpdateSuggestionApiReviewsSuggestionsSuggestionIdPatchMutationOptions =
  <TError = ErrorType<HTTPValidationError>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<
          typeof updateSuggestionApiReviewsSuggestionsSuggestionIdPatch
        >
      >,
      TError,
      { suggestionId: string; data: BodyType<UpdateSuggestionRequest> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  }): UseMutationOptions<
    Awaited<
      ReturnType<typeof updateSuggestionApiReviewsSuggestionsSuggestionIdPatch>
    >,
    TError,
    { suggestionId: string; data: BodyType<UpdateSuggestionRequest> },
    TContext
  > => {
    const mutationKey = [
      "updateSuggestionApiReviewsSuggestionsSuggestionIdPatch",
    ];
    const { mutation: mutationOptions, request: requestOptions } = options
      ? options.mutation &&
        "mutationKey" in options.mutation &&
        options.mutation.mutationKey
        ? options
        : { ...options, mutation: { ...options.mutation, mutationKey } }
      : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
      Awaited<
        ReturnType<
          typeof updateSuggestionApiReviewsSuggestionsSuggestionIdPatch
        >
      >,
      { suggestionId: string; data: BodyType<UpdateSuggestionRequest> }
    > = (props) => {
      const { suggestionId, data } = props ?? {};

      return updateSuggestionApiReviewsSuggestionsSuggestionIdPatch(
        suggestionId,
        data,
        requestOptions,
      );
    };

    return { mutationFn, ...mutationOptions };
  };

export type UpdateSuggestionApiReviewsSuggestionsSuggestionIdPatchMutationResult =
  NonNullable<
    Awaited<
      ReturnType<typeof updateSuggestionApiReviewsSuggestionsSuggestionIdPatch>
    >
  >;
export type UpdateSuggestionApiReviewsSuggestionsSuggestionIdPatchMutationBody =
  BodyType<UpdateSuggestionRequest>;
export type UpdateSuggestionApiReviewsSuggestionsSuggestionIdPatchMutationError =
  ErrorType<HTTPValidationError>;

/**
 * @summary Update Suggestion
 */
export const useUpdateSuggestionApiReviewsSuggestionsSuggestionIdPatch = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<
          typeof updateSuggestionApiReviewsSuggestionsSuggestionIdPatch
        >
      >,
      TError,
      { suggestionId: string; data: BodyType<UpdateSuggestionRequest> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<
    ReturnType<typeof updateSuggestionApiReviewsSuggestionsSuggestionIdPatch>
  >,
  TError,
  { suggestionId: string; data: BodyType<UpdateSuggestionRequest> },
  TContext
> => {
  const mutationOptions =
    getUpdateSuggestionApiReviewsSuggestionsSuggestionIdPatchMutationOptions(
      options,
    );

  return useMutation(mutationOptions, queryClient);
};
