/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";

import type {
  CallLogResponse,
  CallLogSummary,
  GetCallLogSummaryApiCallLogsSummaryGetParams,
  HTTPValidationError,
  ListCallLogsApiCallLogsGetParams,
  RateCallApiCallLogsCallLogIdRatingPatchParams,
} from "../../model";

import { customInstance } from "../../mutator/custom-instance";
import type { ErrorType } from "../../mutator/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * List call logs with optional filters.

Security: Requires JWT authentication. business_id must match authorized tenant.
 * @summary List Call Logs
 */
export const listCallLogsApiCallLogsGet = (
  params: ListCallLogsApiCallLogsGetParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CallLogResponse[]>(
    { url: `/api/call-logs`, method: "GET", params, signal },
    options,
  );
};

export const getListCallLogsApiCallLogsGetQueryKey = (
  params?: ListCallLogsApiCallLogsGetParams,
) => {
  return [`/api/call-logs`, ...(params ? [params] : [])] as const;
};

export const getListCallLogsApiCallLogsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof listCallLogsApiCallLogsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListCallLogsApiCallLogsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listCallLogsApiCallLogsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListCallLogsApiCallLogsGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listCallLogsApiCallLogsGet>>
  > = ({ signal }) =>
    listCallLogsApiCallLogsGet(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listCallLogsApiCallLogsGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListCallLogsApiCallLogsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof listCallLogsApiCallLogsGet>>
>;
export type ListCallLogsApiCallLogsGetQueryError =
  ErrorType<HTTPValidationError>;

export function useListCallLogsApiCallLogsGet<
  TData = Awaited<ReturnType<typeof listCallLogsApiCallLogsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListCallLogsApiCallLogsGetParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listCallLogsApiCallLogsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCallLogsApiCallLogsGet>>,
          TError,
          Awaited<ReturnType<typeof listCallLogsApiCallLogsGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListCallLogsApiCallLogsGet<
  TData = Awaited<ReturnType<typeof listCallLogsApiCallLogsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListCallLogsApiCallLogsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listCallLogsApiCallLogsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCallLogsApiCallLogsGet>>,
          TError,
          Awaited<ReturnType<typeof listCallLogsApiCallLogsGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListCallLogsApiCallLogsGet<
  TData = Awaited<ReturnType<typeof listCallLogsApiCallLogsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListCallLogsApiCallLogsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listCallLogsApiCallLogsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List Call Logs
 */

export function useListCallLogsApiCallLogsGet<
  TData = Awaited<ReturnType<typeof listCallLogsApiCallLogsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListCallLogsApiCallLogsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listCallLogsApiCallLogsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListCallLogsApiCallLogsGetQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getListCallLogsApiCallLogsGetSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof listCallLogsApiCallLogsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListCallLogsApiCallLogsGetParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listCallLogsApiCallLogsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListCallLogsApiCallLogsGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listCallLogsApiCallLogsGet>>
  > = ({ signal }) =>
    listCallLogsApiCallLogsGet(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof listCallLogsApiCallLogsGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListCallLogsApiCallLogsGetSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof listCallLogsApiCallLogsGet>>
>;
export type ListCallLogsApiCallLogsGetSuspenseQueryError =
  ErrorType<HTTPValidationError>;

export function useListCallLogsApiCallLogsGetSuspense<
  TData = Awaited<ReturnType<typeof listCallLogsApiCallLogsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListCallLogsApiCallLogsGetParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listCallLogsApiCallLogsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListCallLogsApiCallLogsGetSuspense<
  TData = Awaited<ReturnType<typeof listCallLogsApiCallLogsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListCallLogsApiCallLogsGetParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listCallLogsApiCallLogsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListCallLogsApiCallLogsGetSuspense<
  TData = Awaited<ReturnType<typeof listCallLogsApiCallLogsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListCallLogsApiCallLogsGetParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listCallLogsApiCallLogsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List Call Logs
 */

export function useListCallLogsApiCallLogsGetSuspense<
  TData = Awaited<ReturnType<typeof listCallLogsApiCallLogsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListCallLogsApiCallLogsGetParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listCallLogsApiCallLogsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListCallLogsApiCallLogsGetSuspenseQueryOptions(
    params,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get summary statistics for call logs.

Security: Requires JWT authentication. business_id must match authorized tenant.
 * @summary Get Call Log Summary
 */
export const getCallLogSummaryApiCallLogsSummaryGet = (
  params: GetCallLogSummaryApiCallLogsSummaryGetParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CallLogSummary>(
    { url: `/api/call-logs/summary`, method: "GET", params, signal },
    options,
  );
};

export const getGetCallLogSummaryApiCallLogsSummaryGetQueryKey = (
  params?: GetCallLogSummaryApiCallLogsSummaryGetParams,
) => {
  return [`/api/call-logs/summary`, ...(params ? [params] : [])] as const;
};

export const getGetCallLogSummaryApiCallLogsSummaryGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getCallLogSummaryApiCallLogsSummaryGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: GetCallLogSummaryApiCallLogsSummaryGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCallLogSummaryApiCallLogsSummaryGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetCallLogSummaryApiCallLogsSummaryGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCallLogSummaryApiCallLogsSummaryGet>>
  > = ({ signal }) =>
    getCallLogSummaryApiCallLogsSummaryGet(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCallLogSummaryApiCallLogsSummaryGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCallLogSummaryApiCallLogsSummaryGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCallLogSummaryApiCallLogsSummaryGet>>
>;
export type GetCallLogSummaryApiCallLogsSummaryGetQueryError =
  ErrorType<HTTPValidationError>;

export function useGetCallLogSummaryApiCallLogsSummaryGet<
  TData = Awaited<ReturnType<typeof getCallLogSummaryApiCallLogsSummaryGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: GetCallLogSummaryApiCallLogsSummaryGetParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCallLogSummaryApiCallLogsSummaryGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCallLogSummaryApiCallLogsSummaryGet>>,
          TError,
          Awaited<ReturnType<typeof getCallLogSummaryApiCallLogsSummaryGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCallLogSummaryApiCallLogsSummaryGet<
  TData = Awaited<ReturnType<typeof getCallLogSummaryApiCallLogsSummaryGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: GetCallLogSummaryApiCallLogsSummaryGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCallLogSummaryApiCallLogsSummaryGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCallLogSummaryApiCallLogsSummaryGet>>,
          TError,
          Awaited<ReturnType<typeof getCallLogSummaryApiCallLogsSummaryGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCallLogSummaryApiCallLogsSummaryGet<
  TData = Awaited<ReturnType<typeof getCallLogSummaryApiCallLogsSummaryGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: GetCallLogSummaryApiCallLogsSummaryGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCallLogSummaryApiCallLogsSummaryGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Call Log Summary
 */

export function useGetCallLogSummaryApiCallLogsSummaryGet<
  TData = Awaited<ReturnType<typeof getCallLogSummaryApiCallLogsSummaryGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: GetCallLogSummaryApiCallLogsSummaryGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCallLogSummaryApiCallLogsSummaryGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCallLogSummaryApiCallLogsSummaryGetQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetCallLogSummaryApiCallLogsSummaryGetSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getCallLogSummaryApiCallLogsSummaryGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: GetCallLogSummaryApiCallLogsSummaryGetParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCallLogSummaryApiCallLogsSummaryGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetCallLogSummaryApiCallLogsSummaryGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCallLogSummaryApiCallLogsSummaryGet>>
  > = ({ signal }) =>
    getCallLogSummaryApiCallLogsSummaryGet(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getCallLogSummaryApiCallLogsSummaryGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCallLogSummaryApiCallLogsSummaryGetSuspenseQueryResult =
  NonNullable<
    Awaited<ReturnType<typeof getCallLogSummaryApiCallLogsSummaryGet>>
  >;
export type GetCallLogSummaryApiCallLogsSummaryGetSuspenseQueryError =
  ErrorType<HTTPValidationError>;

export function useGetCallLogSummaryApiCallLogsSummaryGetSuspense<
  TData = Awaited<ReturnType<typeof getCallLogSummaryApiCallLogsSummaryGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: GetCallLogSummaryApiCallLogsSummaryGetParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCallLogSummaryApiCallLogsSummaryGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCallLogSummaryApiCallLogsSummaryGetSuspense<
  TData = Awaited<ReturnType<typeof getCallLogSummaryApiCallLogsSummaryGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: GetCallLogSummaryApiCallLogsSummaryGetParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCallLogSummaryApiCallLogsSummaryGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCallLogSummaryApiCallLogsSummaryGetSuspense<
  TData = Awaited<ReturnType<typeof getCallLogSummaryApiCallLogsSummaryGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: GetCallLogSummaryApiCallLogsSummaryGetParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCallLogSummaryApiCallLogsSummaryGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Call Log Summary
 */

export function useGetCallLogSummaryApiCallLogsSummaryGetSuspense<
  TData = Awaited<ReturnType<typeof getCallLogSummaryApiCallLogsSummaryGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: GetCallLogSummaryApiCallLogsSummaryGetParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCallLogSummaryApiCallLogsSummaryGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getGetCallLogSummaryApiCallLogsSummaryGetSuspenseQueryOptions(
      params,
      options,
    );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get a call log by ID.

Security: Requires JWT authentication. Call log must belong to authorized tenant.
 * @summary Get Call Log
 */
export const getCallLogApiCallLogsCallLogIdGet = (
  callLogId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CallLogResponse>(
    { url: `/api/call-logs/${callLogId}`, method: "GET", signal },
    options,
  );
};

export const getGetCallLogApiCallLogsCallLogIdGetQueryKey = (
  callLogId?: string,
) => {
  return [`/api/call-logs/${callLogId}`] as const;
};

export const getGetCallLogApiCallLogsCallLogIdGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getCallLogApiCallLogsCallLogIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  callLogId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCallLogApiCallLogsCallLogIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetCallLogApiCallLogsCallLogIdGetQueryKey(callLogId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCallLogApiCallLogsCallLogIdGet>>
  > = ({ signal }) =>
    getCallLogApiCallLogsCallLogIdGet(callLogId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!callLogId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getCallLogApiCallLogsCallLogIdGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCallLogApiCallLogsCallLogIdGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCallLogApiCallLogsCallLogIdGet>>
>;
export type GetCallLogApiCallLogsCallLogIdGetQueryError =
  ErrorType<HTTPValidationError>;

export function useGetCallLogApiCallLogsCallLogIdGet<
  TData = Awaited<ReturnType<typeof getCallLogApiCallLogsCallLogIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  callLogId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCallLogApiCallLogsCallLogIdGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCallLogApiCallLogsCallLogIdGet>>,
          TError,
          Awaited<ReturnType<typeof getCallLogApiCallLogsCallLogIdGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCallLogApiCallLogsCallLogIdGet<
  TData = Awaited<ReturnType<typeof getCallLogApiCallLogsCallLogIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  callLogId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCallLogApiCallLogsCallLogIdGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCallLogApiCallLogsCallLogIdGet>>,
          TError,
          Awaited<ReturnType<typeof getCallLogApiCallLogsCallLogIdGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCallLogApiCallLogsCallLogIdGet<
  TData = Awaited<ReturnType<typeof getCallLogApiCallLogsCallLogIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  callLogId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCallLogApiCallLogsCallLogIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Call Log
 */

export function useGetCallLogApiCallLogsCallLogIdGet<
  TData = Awaited<ReturnType<typeof getCallLogApiCallLogsCallLogIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  callLogId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCallLogApiCallLogsCallLogIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCallLogApiCallLogsCallLogIdGetQueryOptions(
    callLogId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetCallLogApiCallLogsCallLogIdGetSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getCallLogApiCallLogsCallLogIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  callLogId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCallLogApiCallLogsCallLogIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetCallLogApiCallLogsCallLogIdGetQueryKey(callLogId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCallLogApiCallLogsCallLogIdGet>>
  > = ({ signal }) =>
    getCallLogApiCallLogsCallLogIdGet(callLogId, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getCallLogApiCallLogsCallLogIdGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCallLogApiCallLogsCallLogIdGetSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCallLogApiCallLogsCallLogIdGet>>
>;
export type GetCallLogApiCallLogsCallLogIdGetSuspenseQueryError =
  ErrorType<HTTPValidationError>;

export function useGetCallLogApiCallLogsCallLogIdGetSuspense<
  TData = Awaited<ReturnType<typeof getCallLogApiCallLogsCallLogIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  callLogId: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCallLogApiCallLogsCallLogIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCallLogApiCallLogsCallLogIdGetSuspense<
  TData = Awaited<ReturnType<typeof getCallLogApiCallLogsCallLogIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  callLogId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCallLogApiCallLogsCallLogIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCallLogApiCallLogsCallLogIdGetSuspense<
  TData = Awaited<ReturnType<typeof getCallLogApiCallLogsCallLogIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  callLogId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCallLogApiCallLogsCallLogIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Call Log
 */

export function useGetCallLogApiCallLogsCallLogIdGetSuspense<
  TData = Awaited<ReturnType<typeof getCallLogApiCallLogsCallLogIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  callLogId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCallLogApiCallLogsCallLogIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCallLogApiCallLogsCallLogIdGetSuspenseQueryOptions(
    callLogId,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Rate a completed call.

Allows admin to add a rating and optional feedback for call quality tracking.

Security: Requires JWT authentication. Call log must belong to authorized tenant.
 * @summary Rate Call
 */
export const rateCallApiCallLogsCallLogIdRatingPatch = (
  callLogId: string,
  params: RateCallApiCallLogsCallLogIdRatingPatchParams,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<CallLogResponse>(
    { url: `/api/call-logs/${callLogId}/rating`, method: "PATCH", params },
    options,
  );
};

export const getRateCallApiCallLogsCallLogIdRatingPatchMutationOptions = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof rateCallApiCallLogsCallLogIdRatingPatch>>,
    TError,
    {
      callLogId: string;
      params: RateCallApiCallLogsCallLogIdRatingPatchParams;
    },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof rateCallApiCallLogsCallLogIdRatingPatch>>,
  TError,
  { callLogId: string; params: RateCallApiCallLogsCallLogIdRatingPatchParams },
  TContext
> => {
  const mutationKey = ["rateCallApiCallLogsCallLogIdRatingPatch"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof rateCallApiCallLogsCallLogIdRatingPatch>>,
    { callLogId: string; params: RateCallApiCallLogsCallLogIdRatingPatchParams }
  > = (props) => {
    const { callLogId, params } = props ?? {};

    return rateCallApiCallLogsCallLogIdRatingPatch(
      callLogId,
      params,
      requestOptions,
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type RateCallApiCallLogsCallLogIdRatingPatchMutationResult = NonNullable<
  Awaited<ReturnType<typeof rateCallApiCallLogsCallLogIdRatingPatch>>
>;

export type RateCallApiCallLogsCallLogIdRatingPatchMutationError =
  ErrorType<HTTPValidationError>;

/**
 * @summary Rate Call
 */
export const useRateCallApiCallLogsCallLogIdRatingPatch = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof rateCallApiCallLogsCallLogIdRatingPatch>>,
      TError,
      {
        callLogId: string;
        params: RateCallApiCallLogsCallLogIdRatingPatchParams;
      },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof rateCallApiCallLogsCallLogIdRatingPatch>>,
  TError,
  { callLogId: string; params: RateCallApiCallLogsCallLogIdRatingPatchParams },
  TContext
> => {
  const mutationOptions =
    getRateCallApiCallLogsCallLogIdRatingPatchMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
