/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";

import type {
  PlivoHangupWebhookApiPlivoWebhookHangupPost200,
  PlivoHealthApiPlivoHealthGet200,
  PlivoRingingWebhookApiPlivoWebhookRingingPost200,
} from "../../model";

import { customInstance } from "../../mutator/custom-instance";
import type { ErrorType } from "../../mutator/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Handle incoming call answer event from Plivo.

Returns XML that initiates bidirectional audio streaming.

Expected form data:
- CallUUID: Unique call identifier
- From: Caller phone number
- To: Called phone number
- Direction: inbound/outbound
- CallStatus: current call status
 * @summary Plivo Answer Webhook
 */
export const plivoAnswerWebhookApiPlivoWebhookAnswerPost = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    { url: `/api/plivo/webhook/answer`, method: "POST", signal },
    options,
  );
};

export const getPlivoAnswerWebhookApiPlivoWebhookAnswerPostMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof plivoAnswerWebhookApiPlivoWebhookAnswerPost>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof plivoAnswerWebhookApiPlivoWebhookAnswerPost>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["plivoAnswerWebhookApiPlivoWebhookAnswerPost"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof plivoAnswerWebhookApiPlivoWebhookAnswerPost>>,
    void
  > = () => {
    return plivoAnswerWebhookApiPlivoWebhookAnswerPost(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PlivoAnswerWebhookApiPlivoWebhookAnswerPostMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof plivoAnswerWebhookApiPlivoWebhookAnswerPost>>
  >;

export type PlivoAnswerWebhookApiPlivoWebhookAnswerPostMutationError =
  ErrorType<unknown>;

/**
 * @summary Plivo Answer Webhook
 */
export const usePlivoAnswerWebhookApiPlivoWebhookAnswerPost = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof plivoAnswerWebhookApiPlivoWebhookAnswerPost>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof plivoAnswerWebhookApiPlivoWebhookAnswerPost>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions =
    getPlivoAnswerWebhookApiPlivoWebhookAnswerPostMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Handle call hangup event from Plivo.

Logs call metrics and cleans up session.

Expected form data:
- CallUUID: Unique call identifier
- Duration: Call duration in seconds
- HangupCause: Reason for hangup
- EndTime: When call ended
 * @summary Plivo Hangup Webhook
 */
export const plivoHangupWebhookApiPlivoWebhookHangupPost = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<PlivoHangupWebhookApiPlivoWebhookHangupPost200>(
    { url: `/api/plivo/webhook/hangup`, method: "POST", signal },
    options,
  );
};

export const getPlivoHangupWebhookApiPlivoWebhookHangupPostMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof plivoHangupWebhookApiPlivoWebhookHangupPost>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof plivoHangupWebhookApiPlivoWebhookHangupPost>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["plivoHangupWebhookApiPlivoWebhookHangupPost"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof plivoHangupWebhookApiPlivoWebhookHangupPost>>,
    void
  > = () => {
    return plivoHangupWebhookApiPlivoWebhookHangupPost(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PlivoHangupWebhookApiPlivoWebhookHangupPostMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof plivoHangupWebhookApiPlivoWebhookHangupPost>>
  >;

export type PlivoHangupWebhookApiPlivoWebhookHangupPostMutationError =
  ErrorType<unknown>;

/**
 * @summary Plivo Hangup Webhook
 */
export const usePlivoHangupWebhookApiPlivoWebhookHangupPost = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof plivoHangupWebhookApiPlivoWebhookHangupPost>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof plivoHangupWebhookApiPlivoWebhookHangupPost>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions =
    getPlivoHangupWebhookApiPlivoWebhookHangupPostMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Fallback handler for Plivo errors.

Called when the primary answer webhook fails.
Returns a simple apology message and hangs up.
 * @summary Plivo Fallback Webhook
 */
export const plivoFallbackWebhookApiPlivoWebhookFallbackPost = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    { url: `/api/plivo/webhook/fallback`, method: "POST", signal },
    options,
  );
};

export const getPlivoFallbackWebhookApiPlivoWebhookFallbackPostMutationOptions =
  <TError = ErrorType<unknown>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<typeof plivoFallbackWebhookApiPlivoWebhookFallbackPost>
      >,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  }): UseMutationOptions<
    Awaited<ReturnType<typeof plivoFallbackWebhookApiPlivoWebhookFallbackPost>>,
    TError,
    void,
    TContext
  > => {
    const mutationKey = ["plivoFallbackWebhookApiPlivoWebhookFallbackPost"];
    const { mutation: mutationOptions, request: requestOptions } = options
      ? options.mutation &&
        "mutationKey" in options.mutation &&
        options.mutation.mutationKey
        ? options
        : { ...options, mutation: { ...options.mutation, mutationKey } }
      : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
      Awaited<
        ReturnType<typeof plivoFallbackWebhookApiPlivoWebhookFallbackPost>
      >,
      void
    > = () => {
      return plivoFallbackWebhookApiPlivoWebhookFallbackPost(requestOptions);
    };

    return { mutationFn, ...mutationOptions };
  };

export type PlivoFallbackWebhookApiPlivoWebhookFallbackPostMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof plivoFallbackWebhookApiPlivoWebhookFallbackPost>>
  >;

export type PlivoFallbackWebhookApiPlivoWebhookFallbackPostMutationError =
  ErrorType<unknown>;

/**
 * @summary Plivo Fallback Webhook
 */
export const usePlivoFallbackWebhookApiPlivoWebhookFallbackPost = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<typeof plivoFallbackWebhookApiPlivoWebhookFallbackPost>
      >,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof plivoFallbackWebhookApiPlivoWebhookFallbackPost>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions =
    getPlivoFallbackWebhookApiPlivoWebhookFallbackPostMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Handle call ringing event (optional).

Can be used for analytics or early session setup.
 * @summary Plivo Ringing Webhook
 */
export const plivoRingingWebhookApiPlivoWebhookRingingPost = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<PlivoRingingWebhookApiPlivoWebhookRingingPost200>(
    { url: `/api/plivo/webhook/ringing`, method: "POST", signal },
    options,
  );
};

export const getPlivoRingingWebhookApiPlivoWebhookRingingPostMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof plivoRingingWebhookApiPlivoWebhookRingingPost>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof plivoRingingWebhookApiPlivoWebhookRingingPost>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["plivoRingingWebhookApiPlivoWebhookRingingPost"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof plivoRingingWebhookApiPlivoWebhookRingingPost>>,
    void
  > = () => {
    return plivoRingingWebhookApiPlivoWebhookRingingPost(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PlivoRingingWebhookApiPlivoWebhookRingingPostMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof plivoRingingWebhookApiPlivoWebhookRingingPost>>
  >;

export type PlivoRingingWebhookApiPlivoWebhookRingingPostMutationError =
  ErrorType<unknown>;

/**
 * @summary Plivo Ringing Webhook
 */
export const usePlivoRingingWebhookApiPlivoWebhookRingingPost = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof plivoRingingWebhookApiPlivoWebhookRingingPost>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof plivoRingingWebhookApiPlivoWebhookRingingPost>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions =
    getPlivoRingingWebhookApiPlivoWebhookRingingPostMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Check Plivo service health.

Verifies:
- Plivo API credentials are valid
- Call registry is accessible
 * @summary Plivo Health
 */
export const plivoHealthApiPlivoHealthGet = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<PlivoHealthApiPlivoHealthGet200>(
    { url: `/api/plivo/health`, method: "GET", signal },
    options,
  );
};

export const getPlivoHealthApiPlivoHealthGetQueryKey = () => {
  return [`/api/plivo/health`] as const;
};

export const getPlivoHealthApiPlivoHealthGetQueryOptions = <
  TData = Awaited<ReturnType<typeof plivoHealthApiPlivoHealthGet>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof plivoHealthApiPlivoHealthGet>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getPlivoHealthApiPlivoHealthGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof plivoHealthApiPlivoHealthGet>>
  > = ({ signal }) => plivoHealthApiPlivoHealthGet(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof plivoHealthApiPlivoHealthGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PlivoHealthApiPlivoHealthGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof plivoHealthApiPlivoHealthGet>>
>;
export type PlivoHealthApiPlivoHealthGetQueryError = ErrorType<unknown>;

export function usePlivoHealthApiPlivoHealthGet<
  TData = Awaited<ReturnType<typeof plivoHealthApiPlivoHealthGet>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof plivoHealthApiPlivoHealthGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof plivoHealthApiPlivoHealthGet>>,
          TError,
          Awaited<ReturnType<typeof plivoHealthApiPlivoHealthGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePlivoHealthApiPlivoHealthGet<
  TData = Awaited<ReturnType<typeof plivoHealthApiPlivoHealthGet>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof plivoHealthApiPlivoHealthGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof plivoHealthApiPlivoHealthGet>>,
          TError,
          Awaited<ReturnType<typeof plivoHealthApiPlivoHealthGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePlivoHealthApiPlivoHealthGet<
  TData = Awaited<ReturnType<typeof plivoHealthApiPlivoHealthGet>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof plivoHealthApiPlivoHealthGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Plivo Health
 */

export function usePlivoHealthApiPlivoHealthGet<
  TData = Awaited<ReturnType<typeof plivoHealthApiPlivoHealthGet>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof plivoHealthApiPlivoHealthGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPlivoHealthApiPlivoHealthGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getPlivoHealthApiPlivoHealthGetSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof plivoHealthApiPlivoHealthGet>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof plivoHealthApiPlivoHealthGet>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getPlivoHealthApiPlivoHealthGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof plivoHealthApiPlivoHealthGet>>
  > = ({ signal }) => plivoHealthApiPlivoHealthGet(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof plivoHealthApiPlivoHealthGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PlivoHealthApiPlivoHealthGetSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof plivoHealthApiPlivoHealthGet>>
>;
export type PlivoHealthApiPlivoHealthGetSuspenseQueryError = ErrorType<unknown>;

export function usePlivoHealthApiPlivoHealthGetSuspense<
  TData = Awaited<ReturnType<typeof plivoHealthApiPlivoHealthGet>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof plivoHealthApiPlivoHealthGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePlivoHealthApiPlivoHealthGetSuspense<
  TData = Awaited<ReturnType<typeof plivoHealthApiPlivoHealthGet>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof plivoHealthApiPlivoHealthGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePlivoHealthApiPlivoHealthGetSuspense<
  TData = Awaited<ReturnType<typeof plivoHealthApiPlivoHealthGet>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof plivoHealthApiPlivoHealthGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Plivo Health
 */

export function usePlivoHealthApiPlivoHealthGetSuspense<
  TData = Awaited<ReturnType<typeof plivoHealthApiPlivoHealthGet>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof plivoHealthApiPlivoHealthGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getPlivoHealthApiPlivoHealthGetSuspenseQueryOptions(options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
