#!/usr/bin/env bash
# pre-edit-guard.sh — Blocks edits to generated files
# Runs on PreToolUse for Edit and Write tool calls.
# Claude Code passes the tool input as JSON in CLAUDE_TOOL_INPUT.

set -euo pipefail

# Extract file_path from the tool input JSON
FILE_PATH="${CLAUDE_TOOL_INPUT_file_path:-}"

if [[ -z "$FILE_PATH" ]]; then
  # Try parsing from CLAUDE_TOOL_INPUT env var if set
  if [[ -n "${CLAUDE_TOOL_INPUT:-}" ]]; then
    FILE_PATH=$(echo "$CLAUDE_TOOL_INPUT" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('file_path',''))" 2>/dev/null || true)
  fi
fi

if [[ -z "$FILE_PATH" ]]; then
  exit 0  # Can't determine file path, allow the edit
fi

# Normalize: strip leading "./" if present
FILE_PATH="${FILE_PATH#./}"

# Check if the file is in a generated directory

# Pattern 1: src/schemas/*.py — generated Pydantic from JSON Schema
if [[ "$FILE_PATH" =~ ^src/schemas/[^/]+\.py$ ]]; then
  echo "BLOCKED: '$FILE_PATH' is a generated Pydantic schema."
  echo ""
  echo "  DO NOT edit this file manually."
  echo ""
  echo "  Correct workflow:"
  echo "    1. Edit the source JSON schema in schemas/<name>.json"
  echo "    2. Run: ./scripts/generate.sh"
  echo "    3. Then extend src/db/models.py if needed"
  exit 1
fi

# Pattern 2: web/src/api/endpoints/** — generated TypeScript API client
if [[ "$FILE_PATH" =~ ^web/src/api/endpoints/ ]]; then
  echo "BLOCKED: '$FILE_PATH' is a generated TypeScript API client."
  echo ""
  echo "  DO NOT edit this file manually."
  echo ""
  echo "  Correct workflow:"
  echo "    1. Modify the backend route/schema to change the API contract"
  echo "    2. Re-export OpenAPI: python scripts/export_openapi.py"
  echo "    3. Regenerate: cd web && npm run generate:api"
  exit 1
fi

# Pattern 3: web/src/api/model/** — generated TypeScript types
if [[ "$FILE_PATH" =~ ^web/src/api/model/ ]]; then
  echo "BLOCKED: '$FILE_PATH' is a generated TypeScript model/type."
  echo ""
  echo "  DO NOT edit this file manually."
  echo ""
  echo "  Correct workflow:"
  echo "    1. Modify the source JSON schema in schemas/<name>.json"
  echo "    2. Run: ./scripts/generate.sh"
  echo "    3. Re-export OpenAPI: python scripts/export_openapi.py"
  echo "    4. Regenerate TS types: cd web && npm run generate:api"
  exit 1
fi

# File is safe to edit
exit 0
