"""Initial schema - call_logs, reservations, caller_preferences, whatsapp_followups, audit_logs

Revision ID: cafe78f9263c
Revises: 
Create Date: 2026-02-01 03:44:32.172309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cafe78f9263c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('action', sa.Enum('config_update', 'reservation_cancel', 'reservation_modify', 'data_export', 'data_purge', 'login', 'logout', name='auditaction'), nullable=False),
    sa.Column('admin_user', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('call_logs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('business_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('caller_id_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('call_start', sa.DateTime(), nullable=True),
    sa.Column('call_end', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('detected_language', sa.Enum('hindi', 'english', 'hinglish', name='detectedlanguage'), nullable=True),
    sa.Column('transcript', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extracted_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('outcome', sa.Enum('resolved', 'fallback', 'dropped', 'error', 'privacy_opt_out', name='calloutcome'), nullable=True),
    sa.Column('consent_type', sa.Enum('none', 'transcript', 'whatsapp', name='consenttype'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_logs_business_id'), 'call_logs', ['business_id'], unique=False)
    op.create_index(op.f('ix_call_logs_caller_id_hash'), 'call_logs', ['caller_id_hash'], unique=False)
    op.create_index(op.f('ix_call_logs_created_at'), 'call_logs', ['created_at'], unique=False)
    op.create_table('caller_preferences',
    sa.Column('caller_id_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('whatsapp_opt_out', sa.Boolean(), nullable=False),
    sa.Column('transcript_opt_out', sa.Boolean(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('caller_id_hash')
    )
    op.create_table('reservations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('business_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('call_log_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('customer_phone_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('party_size', sa.Integer(), nullable=False),
    sa.Column('reservation_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reservation_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('confirmed', 'cancelled', 'completed', 'no_show', name='reservationstatus'), nullable=False),
    sa.Column('whatsapp_sent', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_consent', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_log_id'], ['call_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservations_business_id'), 'reservations', ['business_id'], unique=False)
    op.create_table('whatsapp_followups',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('business_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('call_log_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_phone_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sa.Enum('callback_request', 'large_party', 'catering_inquiry', 'complaint', 'other', name='followupreason'), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending', 'sent', 'responded', 'expired', name='followupstatus'), nullable=False),
    sa.Column('whatsapp_consent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_log_id'], ['call_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_followups_business_id'), 'whatsapp_followups', ['business_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_followups_status'), 'whatsapp_followups', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_followups_status'), table_name='whatsapp_followups')
    op.drop_index(op.f('ix_whatsapp_followups_business_id'), table_name='whatsapp_followups')
    op.drop_table('whatsapp_followups')
    op.drop_index(op.f('ix_reservations_business_id'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_table('caller_preferences')
    op.drop_index(op.f('ix_call_logs_created_at'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_caller_id_hash'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_business_id'), table_name='call_logs')
    op.drop_table('call_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
