/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";

import type {
  BodyProcessVoiceApiVoiceProcessPost,
  HTTPValidationError,
  TextToSpeechApiVoiceTtsPostBody,
} from "../../model";

import { customInstance } from "../../mutator/custom-instance";
import type { ErrorType, BodyType } from "../../mutator/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Process voice input and return response with audio.
 * @summary Process Voice
 */
export const processVoiceApiVoiceProcessPost = (
  bodyProcessVoiceApiVoiceProcessPost: BodyType<BodyProcessVoiceApiVoiceProcessPost>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  const formData = new FormData();
  formData.append(`audio`, bodyProcessVoiceApiVoiceProcessPost.audio);
  formData.append(`session_id`, bodyProcessVoiceApiVoiceProcessPost.session_id);

  return customInstance<unknown>(
    {
      url: `/api/voice/process`,
      method: "POST",
      headers: { "Content-Type": "multipart/form-data" },
      data: formData,
      signal,
    },
    options,
  );
};

export const getProcessVoiceApiVoiceProcessPostMutationOptions = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof processVoiceApiVoiceProcessPost>>,
    TError,
    { data: BodyType<BodyProcessVoiceApiVoiceProcessPost> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof processVoiceApiVoiceProcessPost>>,
  TError,
  { data: BodyType<BodyProcessVoiceApiVoiceProcessPost> },
  TContext
> => {
  const mutationKey = ["processVoiceApiVoiceProcessPost"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof processVoiceApiVoiceProcessPost>>,
    { data: BodyType<BodyProcessVoiceApiVoiceProcessPost> }
  > = (props) => {
    const { data } = props ?? {};

    return processVoiceApiVoiceProcessPost(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ProcessVoiceApiVoiceProcessPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof processVoiceApiVoiceProcessPost>>
>;
export type ProcessVoiceApiVoiceProcessPostMutationBody =
  BodyType<BodyProcessVoiceApiVoiceProcessPost>;
export type ProcessVoiceApiVoiceProcessPostMutationError =
  ErrorType<HTTPValidationError>;

/**
 * @summary Process Voice
 */
export const useProcessVoiceApiVoiceProcessPost = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof processVoiceApiVoiceProcessPost>>,
      TError,
      { data: BodyType<BodyProcessVoiceApiVoiceProcessPost> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof processVoiceApiVoiceProcessPost>>,
  TError,
  { data: BodyType<BodyProcessVoiceApiVoiceProcessPost> },
  TContext
> => {
  const mutationOptions =
    getProcessVoiceApiVoiceProcessPostMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Serve generated audio file.
 * @summary Get Audio
 */
export const getAudioApiVoiceAudioFilenameGet = (
  filename: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    { url: `/api/voice/audio/${filename}`, method: "GET", signal },
    options,
  );
};

export const getGetAudioApiVoiceAudioFilenameGetQueryKey = (
  filename?: string,
) => {
  return [`/api/voice/audio/${filename}`] as const;
};

export const getGetAudioApiVoiceAudioFilenameGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getAudioApiVoiceAudioFilenameGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  filename: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAudioApiVoiceAudioFilenameGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetAudioApiVoiceAudioFilenameGetQueryKey(filename);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAudioApiVoiceAudioFilenameGet>>
  > = ({ signal }) =>
    getAudioApiVoiceAudioFilenameGet(filename, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!filename,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAudioApiVoiceAudioFilenameGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAudioApiVoiceAudioFilenameGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAudioApiVoiceAudioFilenameGet>>
>;
export type GetAudioApiVoiceAudioFilenameGetQueryError =
  ErrorType<HTTPValidationError>;

export function useGetAudioApiVoiceAudioFilenameGet<
  TData = Awaited<ReturnType<typeof getAudioApiVoiceAudioFilenameGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  filename: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAudioApiVoiceAudioFilenameGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAudioApiVoiceAudioFilenameGet>>,
          TError,
          Awaited<ReturnType<typeof getAudioApiVoiceAudioFilenameGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAudioApiVoiceAudioFilenameGet<
  TData = Awaited<ReturnType<typeof getAudioApiVoiceAudioFilenameGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  filename: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAudioApiVoiceAudioFilenameGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAudioApiVoiceAudioFilenameGet>>,
          TError,
          Awaited<ReturnType<typeof getAudioApiVoiceAudioFilenameGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAudioApiVoiceAudioFilenameGet<
  TData = Awaited<ReturnType<typeof getAudioApiVoiceAudioFilenameGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  filename: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAudioApiVoiceAudioFilenameGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Audio
 */

export function useGetAudioApiVoiceAudioFilenameGet<
  TData = Awaited<ReturnType<typeof getAudioApiVoiceAudioFilenameGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  filename: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAudioApiVoiceAudioFilenameGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAudioApiVoiceAudioFilenameGetQueryOptions(
    filename,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetAudioApiVoiceAudioFilenameGetSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getAudioApiVoiceAudioFilenameGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  filename: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAudioApiVoiceAudioFilenameGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetAudioApiVoiceAudioFilenameGetQueryKey(filename);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAudioApiVoiceAudioFilenameGet>>
  > = ({ signal }) =>
    getAudioApiVoiceAudioFilenameGet(filename, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getAudioApiVoiceAudioFilenameGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAudioApiVoiceAudioFilenameGetSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAudioApiVoiceAudioFilenameGet>>
>;
export type GetAudioApiVoiceAudioFilenameGetSuspenseQueryError =
  ErrorType<HTTPValidationError>;

export function useGetAudioApiVoiceAudioFilenameGetSuspense<
  TData = Awaited<ReturnType<typeof getAudioApiVoiceAudioFilenameGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  filename: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAudioApiVoiceAudioFilenameGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAudioApiVoiceAudioFilenameGetSuspense<
  TData = Awaited<ReturnType<typeof getAudioApiVoiceAudioFilenameGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  filename: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAudioApiVoiceAudioFilenameGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAudioApiVoiceAudioFilenameGetSuspense<
  TData = Awaited<ReturnType<typeof getAudioApiVoiceAudioFilenameGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  filename: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAudioApiVoiceAudioFilenameGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Audio
 */

export function useGetAudioApiVoiceAudioFilenameGetSuspense<
  TData = Awaited<ReturnType<typeof getAudioApiVoiceAudioFilenameGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  filename: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAudioApiVoiceAudioFilenameGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAudioApiVoiceAudioFilenameGetSuspenseQueryOptions(
    filename,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Generate TTS audio from text.
 * @summary Text To Speech
 */
export const textToSpeechApiVoiceTtsPost = (
  textToSpeechApiVoiceTtsPostBody: BodyType<TextToSpeechApiVoiceTtsPostBody>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    {
      url: `/api/voice/tts`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: textToSpeechApiVoiceTtsPostBody,
      signal,
    },
    options,
  );
};

export const getTextToSpeechApiVoiceTtsPostMutationOptions = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof textToSpeechApiVoiceTtsPost>>,
    TError,
    { data: BodyType<TextToSpeechApiVoiceTtsPostBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof textToSpeechApiVoiceTtsPost>>,
  TError,
  { data: BodyType<TextToSpeechApiVoiceTtsPostBody> },
  TContext
> => {
  const mutationKey = ["textToSpeechApiVoiceTtsPost"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof textToSpeechApiVoiceTtsPost>>,
    { data: BodyType<TextToSpeechApiVoiceTtsPostBody> }
  > = (props) => {
    const { data } = props ?? {};

    return textToSpeechApiVoiceTtsPost(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TextToSpeechApiVoiceTtsPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof textToSpeechApiVoiceTtsPost>>
>;
export type TextToSpeechApiVoiceTtsPostMutationBody =
  BodyType<TextToSpeechApiVoiceTtsPostBody>;
export type TextToSpeechApiVoiceTtsPostMutationError =
  ErrorType<HTTPValidationError>;

/**
 * @summary Text To Speech
 */
export const useTextToSpeechApiVoiceTtsPost = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof textToSpeechApiVoiceTtsPost>>,
      TError,
      { data: BodyType<TextToSpeechApiVoiceTtsPostBody> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof textToSpeechApiVoiceTtsPost>>,
  TError,
  { data: BodyType<TextToSpeechApiVoiceTtsPostBody> },
  TContext
> => {
  const mutationOptions =
    getTextToSpeechApiVoiceTtsPostMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
