/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */

/**
 * Business account status.
 */
export type BusinessStatus =
  (typeof BusinessStatus)[keyof typeof BusinessStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BusinessStatus = {
  active: "active",
  suspended: "suspended",
  onboarding: "onboarding",
} as const;
