/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */
import type { BusinessType } from "./businessType";
import type { BusinessStatus } from "./businessStatus";
import type { BusinessResponseOperatingHours } from "./businessResponseOperatingHours";
import type { ReservationRules } from "./reservationRules";
import type { BusinessResponseGreetingText } from "./businessResponseGreetingText";
import type { BusinessResponseMenuSummary } from "./businessResponseMenuSummary";

/**
 * Business settings response.
 */
export interface BusinessResponse {
  id: string;
  name: string;
  type: BusinessType;
  timezone: string;
  status: BusinessStatus;
  phone_numbers: string[];
  operating_hours: BusinessResponseOperatingHours;
  reservation_rules: ReservationRules;
  greeting_text: BusinessResponseGreetingText;
  menu_summary: BusinessResponseMenuSummary;
}
