/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */

/**
 * Type of business.
 */
export type BusinessType = (typeof BusinessType)[keyof typeof BusinessType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BusinessType = {
  restaurant: "restaurant",
  clinic: "clinic",
  salon: "salon",
  other: "other",
} as const;
