/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */
import type { BusinessUpdateName } from "./businessUpdateName";
import type { BusinessUpdateTimezone } from "./businessUpdateTimezone";
import type { BusinessUpdatePhoneNumbers } from "./businessUpdatePhoneNumbers";
import type { BusinessUpdateOperatingHours } from "./businessUpdateOperatingHours";
import type { BusinessUpdateReservationRules } from "./businessUpdateReservationRules";
import type { BusinessUpdateGreetingText } from "./businessUpdateGreetingText";
import type { BusinessUpdateMenuSummary } from "./businessUpdateMenuSummary";

/**
 * Business settings update request.
 */
export interface BusinessUpdate {
  name?: BusinessUpdateName;
  timezone?: BusinessUpdateTimezone;
  phone_numbers?: BusinessUpdatePhoneNumbers;
  operating_hours?: BusinessUpdateOperatingHours;
  reservation_rules?: BusinessUpdateReservationRules;
  greeting_text?: BusinessUpdateGreetingText;
  menu_summary?: BusinessUpdateMenuSummary;
}
