/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */

/**
 * Category/intent of a call.
 */
export type CallCategory = (typeof CallCategory)[keyof typeof CallCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CallCategory = {
  booking: "booking",
  inquiry: "inquiry",
  complaint: "complaint",
  spam: "spam",
  other: "other",
} as const;
