/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */
import type { CallLogResponseCallerIdHash } from "./callLogResponseCallerIdHash";
import type { CallLogResponseCallEnd } from "./callLogResponseCallEnd";
import type { CallLogResponseDurationSeconds } from "./callLogResponseDurationSeconds";
import type { CallLogResponseDetectedLanguage } from "./callLogResponseDetectedLanguage";
import type { CallLogResponseTranscript } from "./callLogResponseTranscript";
import type { CallLogResponseExtractedInfo } from "./callLogResponseExtractedInfo";
import type { CallLogResponseOutcome } from "./callLogResponseOutcome";
import type { CallLogResponseConsentType } from "./callLogResponseConsentType";
import type { CallLogResponseSttLatencyP50Ms } from "./callLogResponseSttLatencyP50Ms";
import type { CallLogResponseLlmLatencyP50Ms } from "./callLogResponseLlmLatencyP50Ms";
import type { CallLogResponseTtsLatencyP50Ms } from "./callLogResponseTtsLatencyP50Ms";
import type { CallLogResponseCallRating } from "./callLogResponseCallRating";
import type { CallLogResponseCallerFeedback } from "./callLogResponseCallerFeedback";
import type { CallLogResponseRatingMethod } from "./callLogResponseRatingMethod";
import type { CallLogResponseCallSummary } from "./callLogResponseCallSummary";
import type { CallLogResponseCallCategory } from "./callLogResponseCallCategory";
import type { CallSource } from "./callSource";

/**
 * Response schema for call logs.
 */
export interface CallLogResponse {
  id: string;
  business_id: string;
  caller_id_hash: CallLogResponseCallerIdHash;
  call_start: string;
  call_end: CallLogResponseCallEnd;
  duration_seconds: CallLogResponseDurationSeconds;
  detected_language: CallLogResponseDetectedLanguage;
  transcript: CallLogResponseTranscript;
  extracted_info: CallLogResponseExtractedInfo;
  outcome: CallLogResponseOutcome;
  consent_type: CallLogResponseConsentType;
  created_at: string;
  stt_latency_p50_ms?: CallLogResponseSttLatencyP50Ms;
  llm_latency_p50_ms?: CallLogResponseLlmLatencyP50Ms;
  tts_latency_p50_ms?: CallLogResponseTtsLatencyP50Ms;
  barge_in_count?: number;
  total_turns?: number;
  call_rating?: CallLogResponseCallRating;
  caller_feedback?: CallLogResponseCallerFeedback;
  rating_method?: CallLogResponseRatingMethod;
  call_summary?: CallLogResponseCallSummary;
  call_category?: CallLogResponseCallCategory;
  call_source?: CallSource;
}
