/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */

/**
 * How a call ended.
 */
export type CallOutcome = (typeof CallOutcome)[keyof typeof CallOutcome];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CallOutcome = {
  resolved: "resolved",
  fallback: "fallback",
  dropped: "dropped",
  error: "error",
  privacy_opt_out: "privacy_opt_out",
} as const;
