/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */
import type { CallLogResponseCallerIdHash } from "./callLogResponseCallerIdHash";
import type { CallLogResponseCallEnd } from "./callLogResponseCallEnd";
import type { CallLogResponseDurationSeconds } from "./callLogResponseDurationSeconds";
import type { CallLogResponseDetectedLanguage } from "./callLogResponseDetectedLanguage";
import type { CallLogResponseTranscript } from "./callLogResponseTranscript";
import type { CallLogResponseExtractedInfo } from "./callLogResponseExtractedInfo";
import type { CallLogResponseOutcome } from "./callLogResponseOutcome";
import type { CallLogResponseConsentType } from "./callLogResponseConsentType";

/**
 * Response schema for call logs.
 */
export interface CallLogResponse {
  id: string;
  business_id: string;
  caller_id_hash: CallLogResponseCallerIdHash;
  call_start: string;
  call_end: CallLogResponseCallEnd;
  duration_seconds: CallLogResponseDurationSeconds;
  detected_language: CallLogResponseDetectedLanguage;
  transcript: CallLogResponseTranscript;
  extracted_info: CallLogResponseExtractedInfo;
  outcome: CallLogResponseOutcome;
  consent_type: CallLogResponseConsentType;
  created_at: string;
}
