/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */

/**
 * Source of the call.
 */
export type CallSource = (typeof CallSource)[keyof typeof CallSource];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CallSource = {
  phone: "phone",
  voice_test: "voice_test",
} as const;
