/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */
import type { CallLogSummaryCallsByOutcome } from "./callLogSummaryCallsByOutcome";
import type { CallLogSummaryCallsByLanguage } from "./callLogSummaryCallsByLanguage";

/**
 * Summary stats for call logs.
 */
export interface CallLogSummary {
  total_calls: number;
  total_duration_seconds: number;
  avg_duration_seconds: number;
  calls_by_outcome: CallLogSummaryCallsByOutcome;
  calls_by_language: CallLogSummaryCallsByLanguage;
}
