/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */

/**
 * Level of consent given by caller.
 */
export type ConsentType = (typeof ConsentType)[keyof typeof ConsentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConsentType = {
  none: "none",
  transcript: "transcript",
  whatsapp: "whatsapp",
} as const;
