/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */
import type { DetailedHealthResponseChecks } from "./detailedHealthResponseChecks";

/**
 * Detailed health check response.
 */
export interface DetailedHealthResponse {
  status: string;
  checks: DetailedHealthResponseChecks;
  version: string;
}
