/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */

/**
 * Detected language during call.
 */
export type DetectedLanguage =
  (typeof DetectedLanguage)[keyof typeof DetectedLanguage];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DetectedLanguage = {
  hindi: "hindi",
  english: "english",
  hinglish: "hinglish",
} as const;
