/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request body for ending a voice test session.
 */
export interface EndSessionRequest {
  session_id: string;
}
