/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response for ending a voice test session.
 */
export interface EndSessionResponse {
  call_log_id: string;
  total_turns: number;
  analysis_queued: boolean;
}
