/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */

export type GetCallLogSummaryApiCallLogsSummaryGetParams = {
  /**
   * Required for tenant isolation
   */
  business_id: string;
  date_from?: string | null;
  date_to?: string | null;
};
