/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */
import type { IssueCategory } from "./issueCategory";
import type { SuggestionStatus } from "./suggestionStatus";
import type { ImprovementSuggestionResponseImplementedAt } from "./improvementSuggestionResponseImplementedAt";
import type { ImprovementSuggestionResponseImplementedBy } from "./improvementSuggestionResponseImplementedBy";
import type { ImprovementSuggestionResponseRejectionReason } from "./improvementSuggestionResponseRejectionReason";

/**
 * Response schema for improvement suggestions.
 */
export interface ImprovementSuggestionResponse {
  id: string;
  review_id: string;
  business_id: string;
  category: IssueCategory;
  title: string;
  description: string;
  priority: number;
  status: SuggestionStatus;
  implemented_at: ImprovementSuggestionResponseImplementedAt;
  implemented_by: ImprovementSuggestionResponseImplementedBy;
  rejection_reason: ImprovementSuggestionResponseRejectionReason;
  created_at: string;
  updated_at: string;
}
