/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */

/**
 * Category of issue identified in transcript review.
 */
export type IssueCategory = (typeof IssueCategory)[keyof typeof IssueCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IssueCategory = {
  knowledge_gap: "knowledge_gap",
  prompt_weakness: "prompt_weakness",
  ux_issue: "ux_issue",
  stt_error: "stt_error",
  tts_issue: "tts_issue",
  config_error: "config_error",
} as const;
