/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */

/**
 * Similarity score (0.0-1.0) or null for keyword-only matches
 */
export type KnowledgeSearchResultScore = number | null;
