/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */
import type { KnowledgeItemUpdateCategory } from "./knowledgeItemUpdateCategory";
import type { KnowledgeItemUpdateTitle } from "./knowledgeItemUpdateTitle";
import type { KnowledgeItemUpdateTitleHindi } from "./knowledgeItemUpdateTitleHindi";
import type { KnowledgeItemUpdateContent } from "./knowledgeItemUpdateContent";
import type { KnowledgeItemUpdateContentHindi } from "./knowledgeItemUpdateContentHindi";
import type { KnowledgeItemUpdateMetadataJson } from "./knowledgeItemUpdateMetadataJson";
import type { KnowledgeItemUpdateIsActive } from "./knowledgeItemUpdateIsActive";
import type { KnowledgeItemUpdatePriority } from "./knowledgeItemUpdatePriority";

/**
 * Schema for updating a knowledge item (all fields optional).
 */
export interface KnowledgeItemUpdate {
  category?: KnowledgeItemUpdateCategory;
  title?: KnowledgeItemUpdateTitle;
  title_hindi?: KnowledgeItemUpdateTitleHindi;
  content?: KnowledgeItemUpdateContent;
  content_hindi?: KnowledgeItemUpdateContentHindi;
  metadata_json?: KnowledgeItemUpdateMetadataJson;
  is_active?: KnowledgeItemUpdateIsActive;
  priority?: KnowledgeItemUpdatePriority;
}
