/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */
import type { KnowledgeCategory } from "./knowledgeCategory";
import type { KnowledgeItemCreateTitleHindi } from "./knowledgeItemCreateTitleHindi";
import type { KnowledgeItemCreateContentHindi } from "./knowledgeItemCreateContentHindi";
import type { KnowledgeItemCreateMetadataJson } from "./knowledgeItemCreateMetadataJson";

/**
 * Schema for creating a knowledge item.
 */
export interface KnowledgeItemCreate {
  business_id: string;
  category: KnowledgeCategory;
  /** @maxLength 200 */
  title: string;
  title_hindi?: KnowledgeItemCreateTitleHindi;
  /** @maxLength 2000 */
  content: string;
  content_hindi?: KnowledgeItemCreateContentHindi;
  metadata_json?: KnowledgeItemCreateMetadataJson;
  is_active?: boolean;
  /**
   * @minimum 0
   * @maximum 100
   */
  priority?: number;
}
