/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */
import type { KnowledgeCategory } from "./knowledgeCategory";

export type KnowledgeItemUpdateCategory = KnowledgeCategory | null;
