/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */
import type { KnowledgeCategory } from "./knowledgeCategory";
import type { KnowledgeItemResponseTitleHindi } from "./knowledgeItemResponseTitleHindi";
import type { KnowledgeItemResponseContentHindi } from "./knowledgeItemResponseContentHindi";
import type { KnowledgeItemResponseMetadataJson } from "./knowledgeItemResponseMetadataJson";
import type { KnowledgeItemResponseEmbeddingId } from "./knowledgeItemResponseEmbeddingId";

/**
 * Response schema for knowledge items.
 */
export interface KnowledgeItemResponse {
  id: string;
  business_id: string;
  category: KnowledgeCategory;
  title: string;
  title_hindi: KnowledgeItemResponseTitleHindi;
  content: string;
  content_hindi: KnowledgeItemResponseContentHindi;
  metadata_json: KnowledgeItemResponseMetadataJson;
  is_active: boolean;
  priority: number;
  embedding_id: KnowledgeItemResponseEmbeddingId;
  created_at: string;
  updated_at: string;
}
