/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */
import type { KnowledgeItemResponse } from "./knowledgeItemResponse";
import type { KnowledgeSearchResultScore } from "./knowledgeSearchResultScore";

/**
 * Search result with similarity score.

When using vector search, score is a real similarity value (0.0-1.0).
When falling back to keyword search, score is None.
 */
export interface KnowledgeSearchResult {
  item: KnowledgeItemResponse;
  /** Similarity score (0.0-1.0) or null for keyword-only matches */
  score?: KnowledgeSearchResultScore;
}
