/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */

/**
 * Category of knowledge item.
 */
export type KnowledgeCategory =
  (typeof KnowledgeCategory)[keyof typeof KnowledgeCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const KnowledgeCategory = {
  menu_item: "menu_item",
  faq: "faq",
  policy: "policy",
  announcement: "announcement",
} as const;
