/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */
import type { ReservationStatus } from "./reservationStatus";

export type ListReservationsApiReservationsGetParams = {
  business_id?: string | null;
  status?: ReservationStatus | null;
  date_from?: string | null;
  date_to?: string | null;
  /**
   * @minimum 0
   */
  skip?: number;
  /**
   * @minimum 1
   * @maximum 1000
   */
  limit?: number;
};
