/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */
import type { SuggestionStatus } from "./suggestionStatus";
import type { IssueCategory } from "./issueCategory";

export type ListSuggestionsApiReviewsSuggestionsGetParams = {
  /**
   * Business ID for tenant isolation
   */
  business_id: string;
  status?: SuggestionStatus | null;
  category?: IssueCategory | null;
  min_priority?: number | null;
  /**
   * @minimum 0
   */
  skip?: number;
  /**
   * @minimum 1
   * @maximum 200
   */
  limit?: number;
};
