/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */

export type ListReviewsApiReviewsGetParams = {
  /**
   * Business ID for tenant isolation
   */
  business_id: string;
  min_score?: number | null;
  max_score?: number | null;
  /**
   * Filter to reviews with issues
   */
  has_issues?: boolean | null;
  /**
   * @minimum 0
   */
  skip?: number;
  /**
   * @minimum 1
   * @maximum 200
   */
  limit?: number;
};
