/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */
import type { OperatingHoursOpen } from "./operatingHoursOpen";
import type { OperatingHoursClose } from "./operatingHoursClose";

/**
 * Operating hours for a single day.
 */
export interface OperatingHours {
  /** Opening time (HH:MM) or null if closed */
  open?: OperatingHoursOpen;
  /** Closing time (HH:MM) or null if closed */
  close?: OperatingHoursClose;
}
