/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */
import type { RatingMethod } from "./ratingMethod";

export type RateCallApiCallLogsCallLogIdRatingPatchParams = {
  /**
   * Rating from 1-5 stars
   * @minimum 1
   * @maximum 5
   */
  rating: number;
  /**
   * Optional feedback text
   */
  feedback?: string | null;
  /**
   * How rating was collected
   */
  method?: RatingMethod;
};
