/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */

/**
 * How a call rating was collected.
 */
export type RatingMethod = (typeof RatingMethod)[keyof typeof RatingMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RatingMethod = {
  dtmf: "dtmf",
  admin: "admin",
  auto: "auto",
} as const;
