/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */
import type { ReservationUpdateCustomerName } from "./reservationUpdateCustomerName";
import type { ReservationUpdatePartySize } from "./reservationUpdatePartySize";
import type { ReservationUpdateReservationDate } from "./reservationUpdateReservationDate";
import type { ReservationUpdateReservationTime } from "./reservationUpdateReservationTime";
import type { ReservationUpdateStatus } from "./reservationUpdateStatus";
import type { ReservationUpdateNotes } from "./reservationUpdateNotes";
import type { ReservationUpdateWhatsappSent } from "./reservationUpdateWhatsappSent";

/**
 * Schema for updating a reservation (all fields optional).
 */
export interface ReservationUpdate {
  customer_name?: ReservationUpdateCustomerName;
  party_size?: ReservationUpdatePartySize;
  reservation_date?: ReservationUpdateReservationDate;
  reservation_time?: ReservationUpdateReservationTime;
  status?: ReservationUpdateStatus;
  notes?: ReservationUpdateNotes;
  whatsapp_sent?: ReservationUpdateWhatsappSent;
}
