/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */
import type { ReservationResponseCallLogId } from "./reservationResponseCallLogId";
import type { ReservationResponseCustomerName } from "./reservationResponseCustomerName";
import type { ReservationStatus } from "./reservationStatus";
import type { ReservationResponseNotes } from "./reservationResponseNotes";

/**
 * Response schema for reservations.
 */
export interface ReservationResponse {
  id: string;
  business_id: string;
  call_log_id: ReservationResponseCallLogId;
  customer_name: ReservationResponseCustomerName;
  party_size: number;
  reservation_date: string;
  reservation_time: string;
  status: ReservationStatus;
  whatsapp_sent: boolean;
  whatsapp_consent: boolean;
  notes: ReservationResponseNotes;
  created_at: string;
  updated_at: string;
}
