/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */

/**
 * Reservation rules for the business.
 */
export interface ReservationRules {
  /** @minimum 1 */
  min_party_size?: number;
  /** @minimum 1 */
  max_party_size?: number;
  /**
   * Max party size bookable by phone (larger → WhatsApp)
   * @minimum 1
   */
  max_phone_party_size?: number;
  /** @minimum 1 */
  total_seats?: number;
  /**
   * How many days ahead can book
   * @minimum 1
   */
  advance_days?: number;
  /** @minimum 15 */
  slot_duration_minutes?: number;
}
