/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */
import type { ReservationCreateCallLogId } from "./reservationCreateCallLogId";
import type { ReservationCreateCustomerName } from "./reservationCreateCustomerName";
import type { ReservationCreateCustomerPhoneEncrypted } from "./reservationCreateCustomerPhoneEncrypted";
import type { ReservationCreateNotes } from "./reservationCreateNotes";

/**
 * Schema for creating a reservation.
 */
export interface ReservationCreate {
  business_id: string;
  call_log_id?: ReservationCreateCallLogId;
  customer_name?: ReservationCreateCustomerName;
  customer_phone_encrypted?: ReservationCreateCustomerPhoneEncrypted;
  /**
   * @minimum 1
   * @maximum 20
   */
  party_size: number;
  reservation_date: string;
  /** @pattern ^([01]?[0-9]|2[0-3]):[0-5][0-9]$ */
  reservation_time: string;
  notes?: ReservationCreateNotes;
  whatsapp_consent?: boolean;
}
