/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */

/**
 * Statistics about transcript reviews.
 */
export interface ReviewStatsResponse {
  total_reviews: number;
  avg_quality_score: number;
  reviews_with_issues: number;
  knowledge_gaps: number;
  prompt_weaknesses: number;
  ux_issues: number;
  pending_suggestions: number;
}
