/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */
import type { KnowledgeCategory } from "./knowledgeCategory";

export type SearchKnowledgeItemsApiKnowledgeSearchPostParams = {
  /**
   * @minLength 1
   * @maxLength 500
   */
  query: string;
  business_id: string;
  category?: KnowledgeCategory | null;
  /**
   * @minimum 1
   * @maximum 20
   */
  limit?: number;
};
