/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */

/**
 * Status of an improvement suggestion.
 */
export type SuggestionStatus =
  (typeof SuggestionStatus)[keyof typeof SuggestionStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SuggestionStatus = {
  pending: "pending",
  implemented: "implemented",
  rejected: "rejected",
  deferred: "deferred",
} as const;
