/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */
import type { TranscriptReviewResponseIssuesJson } from "./transcriptReviewResponseIssuesJson";
import type { TranscriptReviewResponseSuggestionsJson } from "./transcriptReviewResponseSuggestionsJson";
import type { TranscriptReviewResponseReviewLatencyMs } from "./transcriptReviewResponseReviewLatencyMs";

/**
 * Response schema for transcript reviews.
 */
export interface TranscriptReviewResponse {
  id: string;
  call_log_id: string;
  business_id: string;
  quality_score: number;
  issues_json: TranscriptReviewResponseIssuesJson;
  suggestions_json: TranscriptReviewResponseSuggestionsJson;
  has_unanswered_query: boolean;
  has_knowledge_gap: boolean;
  has_prompt_weakness: boolean;
  has_ux_issue: boolean;
  agent_model: string;
  review_latency_ms: TranscriptReviewResponseReviewLatencyMs;
  reviewed_at: string;
  reviewed_by: string;
}
