/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request to trigger analysis for a call.
 */
export interface TriggerAnalysisRequest {
  /** ID of the call to analyze */
  call_log_id: string;
}
