/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */
import type { SuggestionStatus } from "./suggestionStatus";
import type { UpdateSuggestionRequestRejectionReason } from "./updateSuggestionRequestRejectionReason";

/**
 * Request to update suggestion status.
 */
export interface UpdateSuggestionRequest {
  status: SuggestionStatus;
  rejection_reason?: UpdateSuggestionRequestRejectionReason;
}
