# generated by datamodel-codegen:
#   filename:  audit_log.json

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Annotated

from pydantic import BaseModel, Field


class Action(Enum):
    config_update = 'config_update'
    reservation_cancel = 'reservation_cancel'
    reservation_modify = 'reservation_modify'
    data_export = 'data_export'
    data_purge = 'data_purge'
    login = 'login'
    logout = 'logout'


class AuditLog(BaseModel):
    id: Annotated[
        str | None, Field(description='Unique identifier (UUID as string)')
    ] = None
    timestamp: Annotated[
        datetime | None, Field(description='When the action occurred')
    ] = None
    action: Annotated[Action, Field(description='Type of action performed')]
    admin_user: Annotated[
        str | None, Field(description='Username who performed action')
    ] = None
    details: Annotated[
        str | None, Field(description='JSON string with before/after values')
    ] = None
    ip_address: Annotated[str | None, Field(description='IP address of admin')] = None
