# generated by datamodel-codegen:
#   filename:  business.json

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Annotated

from pydantic import BaseModel, Field


class Type(Enum):
    restaurant = 'restaurant'
    clinic = 'clinic'
    salon = 'salon'
    other = 'other'


class Status(Enum):
    active = 'active'
    suspended = 'suspended'
    onboarding = 'onboarding'


class Business(BaseModel):
    id: Annotated[
        str,
        Field(
            description='Business slug identifier (e.g., himalayan_kitchen)',
            pattern='^[a-z][a-z0-9_]{2,49}$',
        ),
    ]
    name: Annotated[
        str, Field(description='Display name of the business', max_length=200)
    ]
    type: Annotated[Type, Field(description='Type of business')]
    timezone: Annotated[
        str | None, Field(description='IANA timezone (e.g., Asia/Kolkata)')
    ] = 'Asia/Kolkata'
    status: Annotated[Status | None, Field(description='Business account status')] = (
        'onboarding'
    )
    phone_numbers_json: Annotated[
        str | None, Field(description='JSON array of phone numbers in E.164 format')
    ] = None
    operating_hours_json: Annotated[
        str | None,
        Field(
            description='JSON object mapping day names to hours (e.g., {"monday": "closed", "tuesday": "11:00-22:30"})'
        ),
    ] = None
    reservation_rules_json: Annotated[
        str | None,
        Field(
            description='JSON object with reservation rules (min_party_size, max_phone_party_size, total_seats, etc.)'
        ),
    ] = None
    greeting_text: Annotated[
        str | None, Field(description='Custom greeting for voice calls', max_length=500)
    ] = None
    menu_summary: Annotated[
        str | None,
        Field(
            description='Brief menu/service summary for LLM context', max_length=2000
        ),
    ] = None
    admin_password_hash: Annotated[
        str | None, Field(description='bcrypt hash for business-specific admin access')
    ] = None
    created_at: datetime | None = None
    updated_at: datetime | None = None
