# generated by datamodel-codegen:
#   filename:  call_log.json
#   timestamp: 2026-01-31T22:38:13+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field, conint


class DetectedLanguage(Enum):
    hindi = 'hindi'
    english = 'english'
    hinglish = 'hinglish'


class Outcome(Enum):
    resolved = 'resolved'
    fallback = 'fallback'
    dropped = 'dropped'
    error = 'error'
    privacy_opt_out = 'privacy_opt_out'


class ConsentType(Enum):
    none = 'none'
    transcript = 'transcript'
    whatsapp = 'whatsapp'


class CallLog(BaseModel):
    id: str | None = Field(None, description='Unique identifier (UUID)')
    business_id: str = Field(..., description='Business that received this call')
    caller_id_hash: str | None = Field(
        None, description='HMAC-SHA256 hash of caller phone'
    )
    call_start: datetime | None = Field(
        None, description='When call started (set on creation)'
    )
    call_end: datetime | None = Field(None, description='When call ended')
    duration_seconds: conint(ge=0) | None = None  # type: ignore[valid-type]
    detected_language: DetectedLanguage | None = None
    transcript: str | None = Field(
        None, description='JSON string of conversation turns'
    )
    extracted_info: str | None = Field(
        None, description='JSON string of extracted entities'
    )
    outcome: Outcome | None = Field(
        None, description='How the call ended (set when call completes)'
    )
    consent_type: ConsentType | None = None
    created_at: datetime | None = None
