# generated by datamodel-codegen:
#   filename:  caller_preferences.json

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel


class CallerPreferences(BaseModel):
    id: str | None = None
    caller_id_hash: str
    language_preference: str | None = None
    whatsapp_opt_out: bool | None = False
    last_seen: datetime | None = None
