# generated by datamodel-codegen:
#   filename:  call_log.json

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel


class CallLog(BaseModel):
    id: str | None = None
    business_id: str
    caller_id_hash: str | None = None
    call_start: datetime
    call_end: datetime | None = None
    duration_seconds: int | None = None
    detected_language: str | None = None
    transcript: str | None = None
    extracted_info: str | None = None
    outcome: str
    consent_type: str | None = None
    created_at: datetime | None = None
