# generated by datamodel-codegen:
#   filename:  call_log.json

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Annotated

from pydantic import BaseModel, Field


class DetectedLanguage(Enum):
    hindi = 'hindi'
    english = 'english'
    hinglish = 'hinglish'


class Outcome(Enum):
    resolved = 'resolved'
    fallback = 'fallback'
    dropped = 'dropped'
    error = 'error'
    privacy_opt_out = 'privacy_opt_out'


class ConsentType(Enum):
    none = 'none'
    transcript = 'transcript'
    whatsapp = 'whatsapp'


class CallLog(BaseModel):
    id: Annotated[str | None, Field(description='Unique identifier (UUID)')] = None
    business_id: Annotated[str, Field(description='Business that received this call')]
    caller_id_hash: Annotated[
        str | None, Field(description='HMAC-SHA256 hash of caller phone')
    ] = None
    call_start: Annotated[
        datetime | None, Field(description='When call started (set on creation)')
    ] = None
    call_end: Annotated[datetime | None, Field(description='When call ended')] = None
    duration_seconds: Annotated[int | None, Field(ge=0)] = None
    detected_language: DetectedLanguage | None = None
    transcript: Annotated[
        str | None, Field(description='JSON string of conversation turns')
    ] = None
    extracted_info: Annotated[
        str | None, Field(description='JSON string of extracted entities')
    ] = None
    outcome: Annotated[
        Outcome | None,
        Field(description='How the call ended (set when call completes)'),
    ] = None
    consent_type: ConsentType | None = None
    created_at: datetime | None = None
