# generated by datamodel-codegen:
#   filename:  conversation_turn.json

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel


class Speaker(Enum):
    caller = 'caller'
    bot = 'bot'


class ConversationTurn(BaseModel):
    turn_id: int
    speaker: Speaker
    timestamp: datetime
    transcript: str
    detected_language: str | None = None
    intent: str | None = None
    entities: dict[str, Any] | None = None
    response_latency_ms: int | None = None
