# generated by datamodel-codegen:
#   filename:  knowledge_item.json

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Annotated

from pydantic import BaseModel, Field


class Category(Enum):
    menu_item = 'menu_item'
    faq = 'faq'
    policy = 'policy'
    announcement = 'announcement'


class KnowledgeItem(BaseModel):
    id: Annotated[str, Field(description='Unique identifier (UUID)')]
    business_id: Annotated[
        str, Field(description='Business this item belongs to (tenant isolation)')
    ]
    category: Annotated[Category, Field(description='Type of knowledge item')]
    title: Annotated[
        str,
        Field(
            description="Item title (e.g., 'Veg Momos', 'Cancellation Policy')",
            max_length=200,
        ),
    ]
    title_hindi: Annotated[
        str | None,
        Field(
            description='Title in Hindi/Devanagari for better retrieval', max_length=200
        ),
    ] = None
    content: Annotated[
        str, Field(description='Full content/description', max_length=2000)
    ]
    content_hindi: Annotated[
        str | None,
        Field(description='Content in Hindi for bilingual support', max_length=2000),
    ] = None
    metadata_json: Annotated[
        str | None,
        Field(
            description='JSON object with category-specific metadata (price, is_vegetarian, keywords, etc.)'
        ),
    ] = None
    is_active: Annotated[
        bool | None, Field(description='Whether this item is active for retrieval')
    ] = True
    priority: Annotated[
        int | None,
        Field(
            description='Priority for ranking (higher = more important)', ge=0, le=100
        ),
    ] = 50
    embedding_id: Annotated[
        str | None, Field(description='ChromaDB document ID for vector retrieval')
    ] = None
    created_at: datetime | None = None
    updated_at: datetime | None = None
