# generated by datamodel-codegen:
#   filename:  reservation.json

from __future__ import annotations

from datetime import date, datetime
from enum import Enum
from typing import Annotated

from pydantic import BaseModel, Field


class Status(Enum):
    confirmed = 'confirmed'
    cancelled = 'cancelled'
    completed = 'completed'
    no_show = 'no_show'


class Reservation(BaseModel):
    id: Annotated[
        str | None,
        Field(
            description='Unique identifier (UUID as string for SQLite compatibility)'
        ),
    ] = None
    business_id: str
    call_log_id: str | None = None
    customer_name: Annotated[str | None, Field(max_length=100)] = None
    customer_phone_encrypted: str | None = None
    party_size: Annotated[int, Field(ge=1, le=20)]
    reservation_date: date
    reservation_time: Annotated[str, Field(pattern='^([01]?[0-9]|2[0-3]):[0-5][0-9]$')]
    status: Status | None = 'confirmed'  # type: ignore[assignment]
    whatsapp_sent: bool | None = False
    whatsapp_consent: bool | None = False
    notes: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None
