# generated by datamodel-codegen:
#   filename:  whatsapp_followup.json

from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import BaseModel


class Status(Enum):
    pending = 'pending'
    sent = 'sent'
    failed = 'failed'


class WhatsAppFollowup(BaseModel):
    id: str | None = None
    reservation_id: str
    customer_phone_encrypted: str
    message: str | None = None
    status: Status | None = 'pending'
    created_at: datetime | None = None
