/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";

import type {
  BusinessResponse,
  BusinessUpdate,
  HTTPValidationError,
} from "../../model";

import { customInstance } from "../../mutator/custom-instance";
import type { ErrorType, BodyType } from "../../mutator/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Get business settings by ID.

Requires JWT authentication and X-Business-ID header.
User must have access to the requested business.
 * @summary Get Business
 */
export const getBusinessApiBusinessBusinessIdGet = (
  businessId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<BusinessResponse>(
    { url: `/api/business/${businessId}`, method: "GET", signal },
    options,
  );
};

export const getGetBusinessApiBusinessBusinessIdGetQueryKey = (
  businessId?: string,
) => {
  return [`/api/business/${businessId}`] as const;
};

export const getGetBusinessApiBusinessBusinessIdGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getBusinessApiBusinessBusinessIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  businessId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBusinessApiBusinessBusinessIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetBusinessApiBusinessBusinessIdGetQueryKey(businessId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getBusinessApiBusinessBusinessIdGet>>
  > = ({ signal }) =>
    getBusinessApiBusinessBusinessIdGet(businessId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!businessId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getBusinessApiBusinessBusinessIdGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetBusinessApiBusinessBusinessIdGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBusinessApiBusinessBusinessIdGet>>
>;
export type GetBusinessApiBusinessBusinessIdGetQueryError =
  ErrorType<HTTPValidationError>;

export function useGetBusinessApiBusinessBusinessIdGet<
  TData = Awaited<ReturnType<typeof getBusinessApiBusinessBusinessIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  businessId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBusinessApiBusinessBusinessIdGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBusinessApiBusinessBusinessIdGet>>,
          TError,
          Awaited<ReturnType<typeof getBusinessApiBusinessBusinessIdGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBusinessApiBusinessBusinessIdGet<
  TData = Awaited<ReturnType<typeof getBusinessApiBusinessBusinessIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  businessId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBusinessApiBusinessBusinessIdGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBusinessApiBusinessBusinessIdGet>>,
          TError,
          Awaited<ReturnType<typeof getBusinessApiBusinessBusinessIdGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBusinessApiBusinessBusinessIdGet<
  TData = Awaited<ReturnType<typeof getBusinessApiBusinessBusinessIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  businessId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBusinessApiBusinessBusinessIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Business
 */

export function useGetBusinessApiBusinessBusinessIdGet<
  TData = Awaited<ReturnType<typeof getBusinessApiBusinessBusinessIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  businessId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBusinessApiBusinessBusinessIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetBusinessApiBusinessBusinessIdGetQueryOptions(
    businessId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetBusinessApiBusinessBusinessIdGetSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getBusinessApiBusinessBusinessIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  businessId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getBusinessApiBusinessBusinessIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetBusinessApiBusinessBusinessIdGetQueryKey(businessId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getBusinessApiBusinessBusinessIdGet>>
  > = ({ signal }) =>
    getBusinessApiBusinessBusinessIdGet(businessId, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getBusinessApiBusinessBusinessIdGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetBusinessApiBusinessBusinessIdGetSuspenseQueryResult =
  NonNullable<Awaited<ReturnType<typeof getBusinessApiBusinessBusinessIdGet>>>;
export type GetBusinessApiBusinessBusinessIdGetSuspenseQueryError =
  ErrorType<HTTPValidationError>;

export function useGetBusinessApiBusinessBusinessIdGetSuspense<
  TData = Awaited<ReturnType<typeof getBusinessApiBusinessBusinessIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  businessId: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getBusinessApiBusinessBusinessIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBusinessApiBusinessBusinessIdGetSuspense<
  TData = Awaited<ReturnType<typeof getBusinessApiBusinessBusinessIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  businessId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getBusinessApiBusinessBusinessIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBusinessApiBusinessBusinessIdGetSuspense<
  TData = Awaited<ReturnType<typeof getBusinessApiBusinessBusinessIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  businessId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getBusinessApiBusinessBusinessIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Business
 */

export function useGetBusinessApiBusinessBusinessIdGetSuspense<
  TData = Awaited<ReturnType<typeof getBusinessApiBusinessBusinessIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  businessId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getBusinessApiBusinessBusinessIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getGetBusinessApiBusinessBusinessIdGetSuspenseQueryOptions(
      businessId,
      options,
    );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Update business settings.

Requires JWT authentication and X-Business-ID header.
User must have access to the requested business.
 * @summary Update Business
 */
export const updateBusinessApiBusinessBusinessIdPatch = (
  businessId: string,
  businessUpdate: BodyType<BusinessUpdate>,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<BusinessResponse>(
    {
      url: `/api/business/${businessId}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: businessUpdate,
    },
    options,
  );
};

export const getUpdateBusinessApiBusinessBusinessIdPatchMutationOptions = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateBusinessApiBusinessBusinessIdPatch>>,
    TError,
    { businessId: string; data: BodyType<BusinessUpdate> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateBusinessApiBusinessBusinessIdPatch>>,
  TError,
  { businessId: string; data: BodyType<BusinessUpdate> },
  TContext
> => {
  const mutationKey = ["updateBusinessApiBusinessBusinessIdPatch"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateBusinessApiBusinessBusinessIdPatch>>,
    { businessId: string; data: BodyType<BusinessUpdate> }
  > = (props) => {
    const { businessId, data } = props ?? {};

    return updateBusinessApiBusinessBusinessIdPatch(
      businessId,
      data,
      requestOptions,
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateBusinessApiBusinessBusinessIdPatchMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof updateBusinessApiBusinessBusinessIdPatch>>
  >;
export type UpdateBusinessApiBusinessBusinessIdPatchMutationBody =
  BodyType<BusinessUpdate>;
export type UpdateBusinessApiBusinessBusinessIdPatchMutationError =
  ErrorType<HTTPValidationError>;

/**
 * @summary Update Business
 */
export const useUpdateBusinessApiBusinessBusinessIdPatch = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateBusinessApiBusinessBusinessIdPatch>>,
      TError,
      { businessId: string; data: BodyType<BusinessUpdate> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateBusinessApiBusinessBusinessIdPatch>>,
  TError,
  { businessId: string; data: BodyType<BusinessUpdate> },
  TContext
> => {
  const mutationOptions =
    getUpdateBusinessApiBusinessBusinessIdPatchMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
