/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vartalaap API
 * Voice bot platform for local Indian businesses
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";

import type {
  HTTPValidationError,
  KnowledgeItemCreate,
  KnowledgeItemResponse,
  KnowledgeItemUpdate,
  KnowledgeSearchResult,
  ListKnowledgeItemsApiKnowledgeGetParams,
  SearchKnowledgeApiKnowledgeSearchPostParams,
} from "../../model";

import { customInstance } from "../../mutator/custom-instance";
import type { ErrorType, BodyType } from "../../mutator/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * List knowledge items with optional filters.

Security: business_id is required to prevent cross-tenant data access.
 * @summary List Knowledge Items
 */
export const listKnowledgeItemsApiKnowledgeGet = (
  params: ListKnowledgeItemsApiKnowledgeGetParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<KnowledgeItemResponse[]>(
    { url: `/api/knowledge`, method: "GET", params, signal },
    options,
  );
};

export const getListKnowledgeItemsApiKnowledgeGetQueryKey = (
  params?: ListKnowledgeItemsApiKnowledgeGetParams,
) => {
  return [`/api/knowledge`, ...(params ? [params] : [])] as const;
};

export const getListKnowledgeItemsApiKnowledgeGetQueryOptions = <
  TData = Awaited<ReturnType<typeof listKnowledgeItemsApiKnowledgeGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListKnowledgeItemsApiKnowledgeGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listKnowledgeItemsApiKnowledgeGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getListKnowledgeItemsApiKnowledgeGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listKnowledgeItemsApiKnowledgeGet>>
  > = ({ signal }) =>
    listKnowledgeItemsApiKnowledgeGet(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listKnowledgeItemsApiKnowledgeGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListKnowledgeItemsApiKnowledgeGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof listKnowledgeItemsApiKnowledgeGet>>
>;
export type ListKnowledgeItemsApiKnowledgeGetQueryError =
  ErrorType<HTTPValidationError>;

export function useListKnowledgeItemsApiKnowledgeGet<
  TData = Awaited<ReturnType<typeof listKnowledgeItemsApiKnowledgeGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListKnowledgeItemsApiKnowledgeGetParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listKnowledgeItemsApiKnowledgeGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listKnowledgeItemsApiKnowledgeGet>>,
          TError,
          Awaited<ReturnType<typeof listKnowledgeItemsApiKnowledgeGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListKnowledgeItemsApiKnowledgeGet<
  TData = Awaited<ReturnType<typeof listKnowledgeItemsApiKnowledgeGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListKnowledgeItemsApiKnowledgeGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listKnowledgeItemsApiKnowledgeGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listKnowledgeItemsApiKnowledgeGet>>,
          TError,
          Awaited<ReturnType<typeof listKnowledgeItemsApiKnowledgeGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListKnowledgeItemsApiKnowledgeGet<
  TData = Awaited<ReturnType<typeof listKnowledgeItemsApiKnowledgeGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListKnowledgeItemsApiKnowledgeGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listKnowledgeItemsApiKnowledgeGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List Knowledge Items
 */

export function useListKnowledgeItemsApiKnowledgeGet<
  TData = Awaited<ReturnType<typeof listKnowledgeItemsApiKnowledgeGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListKnowledgeItemsApiKnowledgeGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listKnowledgeItemsApiKnowledgeGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListKnowledgeItemsApiKnowledgeGetQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getListKnowledgeItemsApiKnowledgeGetSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof listKnowledgeItemsApiKnowledgeGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListKnowledgeItemsApiKnowledgeGetParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listKnowledgeItemsApiKnowledgeGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getListKnowledgeItemsApiKnowledgeGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listKnowledgeItemsApiKnowledgeGet>>
  > = ({ signal }) =>
    listKnowledgeItemsApiKnowledgeGet(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof listKnowledgeItemsApiKnowledgeGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListKnowledgeItemsApiKnowledgeGetSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof listKnowledgeItemsApiKnowledgeGet>>
>;
export type ListKnowledgeItemsApiKnowledgeGetSuspenseQueryError =
  ErrorType<HTTPValidationError>;

export function useListKnowledgeItemsApiKnowledgeGetSuspense<
  TData = Awaited<ReturnType<typeof listKnowledgeItemsApiKnowledgeGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListKnowledgeItemsApiKnowledgeGetParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listKnowledgeItemsApiKnowledgeGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListKnowledgeItemsApiKnowledgeGetSuspense<
  TData = Awaited<ReturnType<typeof listKnowledgeItemsApiKnowledgeGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListKnowledgeItemsApiKnowledgeGetParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listKnowledgeItemsApiKnowledgeGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListKnowledgeItemsApiKnowledgeGetSuspense<
  TData = Awaited<ReturnType<typeof listKnowledgeItemsApiKnowledgeGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListKnowledgeItemsApiKnowledgeGetParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listKnowledgeItemsApiKnowledgeGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List Knowledge Items
 */

export function useListKnowledgeItemsApiKnowledgeGetSuspense<
  TData = Awaited<ReturnType<typeof listKnowledgeItemsApiKnowledgeGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ListKnowledgeItemsApiKnowledgeGetParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listKnowledgeItemsApiKnowledgeGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListKnowledgeItemsApiKnowledgeGetSuspenseQueryOptions(
    params,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Create a new knowledge item.
 * @summary Create Knowledge Item
 */
export const createKnowledgeItemApiKnowledgePost = (
  knowledgeItemCreate: BodyType<KnowledgeItemCreate>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<KnowledgeItemResponse>(
    {
      url: `/api/knowledge`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: knowledgeItemCreate,
      signal,
    },
    options,
  );
};

export const getCreateKnowledgeItemApiKnowledgePostMutationOptions = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createKnowledgeItemApiKnowledgePost>>,
    TError,
    { data: BodyType<KnowledgeItemCreate> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createKnowledgeItemApiKnowledgePost>>,
  TError,
  { data: BodyType<KnowledgeItemCreate> },
  TContext
> => {
  const mutationKey = ["createKnowledgeItemApiKnowledgePost"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createKnowledgeItemApiKnowledgePost>>,
    { data: BodyType<KnowledgeItemCreate> }
  > = (props) => {
    const { data } = props ?? {};

    return createKnowledgeItemApiKnowledgePost(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateKnowledgeItemApiKnowledgePostMutationResult = NonNullable<
  Awaited<ReturnType<typeof createKnowledgeItemApiKnowledgePost>>
>;
export type CreateKnowledgeItemApiKnowledgePostMutationBody =
  BodyType<KnowledgeItemCreate>;
export type CreateKnowledgeItemApiKnowledgePostMutationError =
  ErrorType<HTTPValidationError>;

/**
 * @summary Create Knowledge Item
 */
export const useCreateKnowledgeItemApiKnowledgePost = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createKnowledgeItemApiKnowledgePost>>,
      TError,
      { data: BodyType<KnowledgeItemCreate> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createKnowledgeItemApiKnowledgePost>>,
  TError,
  { data: BodyType<KnowledgeItemCreate> },
  TContext
> => {
  const mutationOptions =
    getCreateKnowledgeItemApiKnowledgePostMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Get a knowledge item by ID.
 * @summary Get Knowledge Item
 */
export const getKnowledgeItemApiKnowledgeItemIdGet = (
  itemId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<KnowledgeItemResponse>(
    { url: `/api/knowledge/${itemId}`, method: "GET", signal },
    options,
  );
};

export const getGetKnowledgeItemApiKnowledgeItemIdGetQueryKey = (
  itemId?: string,
) => {
  return [`/api/knowledge/${itemId}`] as const;
};

export const getGetKnowledgeItemApiKnowledgeItemIdGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getKnowledgeItemApiKnowledgeItemIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  itemId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getKnowledgeItemApiKnowledgeItemIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetKnowledgeItemApiKnowledgeItemIdGetQueryKey(itemId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getKnowledgeItemApiKnowledgeItemIdGet>>
  > = ({ signal }) =>
    getKnowledgeItemApiKnowledgeItemIdGet(itemId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!itemId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getKnowledgeItemApiKnowledgeItemIdGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetKnowledgeItemApiKnowledgeItemIdGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getKnowledgeItemApiKnowledgeItemIdGet>>
>;
export type GetKnowledgeItemApiKnowledgeItemIdGetQueryError =
  ErrorType<HTTPValidationError>;

export function useGetKnowledgeItemApiKnowledgeItemIdGet<
  TData = Awaited<ReturnType<typeof getKnowledgeItemApiKnowledgeItemIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  itemId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getKnowledgeItemApiKnowledgeItemIdGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getKnowledgeItemApiKnowledgeItemIdGet>>,
          TError,
          Awaited<ReturnType<typeof getKnowledgeItemApiKnowledgeItemIdGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetKnowledgeItemApiKnowledgeItemIdGet<
  TData = Awaited<ReturnType<typeof getKnowledgeItemApiKnowledgeItemIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  itemId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getKnowledgeItemApiKnowledgeItemIdGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getKnowledgeItemApiKnowledgeItemIdGet>>,
          TError,
          Awaited<ReturnType<typeof getKnowledgeItemApiKnowledgeItemIdGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetKnowledgeItemApiKnowledgeItemIdGet<
  TData = Awaited<ReturnType<typeof getKnowledgeItemApiKnowledgeItemIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  itemId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getKnowledgeItemApiKnowledgeItemIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Knowledge Item
 */

export function useGetKnowledgeItemApiKnowledgeItemIdGet<
  TData = Awaited<ReturnType<typeof getKnowledgeItemApiKnowledgeItemIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  itemId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getKnowledgeItemApiKnowledgeItemIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetKnowledgeItemApiKnowledgeItemIdGetQueryOptions(
    itemId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetKnowledgeItemApiKnowledgeItemIdGetSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getKnowledgeItemApiKnowledgeItemIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  itemId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getKnowledgeItemApiKnowledgeItemIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetKnowledgeItemApiKnowledgeItemIdGetQueryKey(itemId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getKnowledgeItemApiKnowledgeItemIdGet>>
  > = ({ signal }) =>
    getKnowledgeItemApiKnowledgeItemIdGet(itemId, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getKnowledgeItemApiKnowledgeItemIdGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetKnowledgeItemApiKnowledgeItemIdGetSuspenseQueryResult =
  NonNullable<
    Awaited<ReturnType<typeof getKnowledgeItemApiKnowledgeItemIdGet>>
  >;
export type GetKnowledgeItemApiKnowledgeItemIdGetSuspenseQueryError =
  ErrorType<HTTPValidationError>;

export function useGetKnowledgeItemApiKnowledgeItemIdGetSuspense<
  TData = Awaited<ReturnType<typeof getKnowledgeItemApiKnowledgeItemIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  itemId: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getKnowledgeItemApiKnowledgeItemIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetKnowledgeItemApiKnowledgeItemIdGetSuspense<
  TData = Awaited<ReturnType<typeof getKnowledgeItemApiKnowledgeItemIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  itemId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getKnowledgeItemApiKnowledgeItemIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetKnowledgeItemApiKnowledgeItemIdGetSuspense<
  TData = Awaited<ReturnType<typeof getKnowledgeItemApiKnowledgeItemIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  itemId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getKnowledgeItemApiKnowledgeItemIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Knowledge Item
 */

export function useGetKnowledgeItemApiKnowledgeItemIdGetSuspense<
  TData = Awaited<ReturnType<typeof getKnowledgeItemApiKnowledgeItemIdGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  itemId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getKnowledgeItemApiKnowledgeItemIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getGetKnowledgeItemApiKnowledgeItemIdGetSuspenseQueryOptions(
      itemId,
      options,
    );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Update a knowledge item (partial update).
 * @summary Update Knowledge Item
 */
export const updateKnowledgeItemApiKnowledgeItemIdPatch = (
  itemId: string,
  knowledgeItemUpdate: BodyType<KnowledgeItemUpdate>,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<KnowledgeItemResponse>(
    {
      url: `/api/knowledge/${itemId}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: knowledgeItemUpdate,
    },
    options,
  );
};

export const getUpdateKnowledgeItemApiKnowledgeItemIdPatchMutationOptions = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateKnowledgeItemApiKnowledgeItemIdPatch>>,
    TError,
    { itemId: string; data: BodyType<KnowledgeItemUpdate> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateKnowledgeItemApiKnowledgeItemIdPatch>>,
  TError,
  { itemId: string; data: BodyType<KnowledgeItemUpdate> },
  TContext
> => {
  const mutationKey = ["updateKnowledgeItemApiKnowledgeItemIdPatch"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateKnowledgeItemApiKnowledgeItemIdPatch>>,
    { itemId: string; data: BodyType<KnowledgeItemUpdate> }
  > = (props) => {
    const { itemId, data } = props ?? {};

    return updateKnowledgeItemApiKnowledgeItemIdPatch(
      itemId,
      data,
      requestOptions,
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateKnowledgeItemApiKnowledgeItemIdPatchMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof updateKnowledgeItemApiKnowledgeItemIdPatch>>
  >;
export type UpdateKnowledgeItemApiKnowledgeItemIdPatchMutationBody =
  BodyType<KnowledgeItemUpdate>;
export type UpdateKnowledgeItemApiKnowledgeItemIdPatchMutationError =
  ErrorType<HTTPValidationError>;

/**
 * @summary Update Knowledge Item
 */
export const useUpdateKnowledgeItemApiKnowledgeItemIdPatch = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateKnowledgeItemApiKnowledgeItemIdPatch>>,
      TError,
      { itemId: string; data: BodyType<KnowledgeItemUpdate> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateKnowledgeItemApiKnowledgeItemIdPatch>>,
  TError,
  { itemId: string; data: BodyType<KnowledgeItemUpdate> },
  TContext
> => {
  const mutationOptions =
    getUpdateKnowledgeItemApiKnowledgeItemIdPatchMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Delete a knowledge item.
 * @summary Delete Knowledge Item
 */
export const deleteKnowledgeItemApiKnowledgeItemIdDelete = (
  itemId: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    { url: `/api/knowledge/${itemId}`, method: "DELETE" },
    options,
  );
};

export const getDeleteKnowledgeItemApiKnowledgeItemIdDeleteMutationOptions = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteKnowledgeItemApiKnowledgeItemIdDelete>>,
    TError,
    { itemId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteKnowledgeItemApiKnowledgeItemIdDelete>>,
  TError,
  { itemId: string },
  TContext
> => {
  const mutationKey = ["deleteKnowledgeItemApiKnowledgeItemIdDelete"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteKnowledgeItemApiKnowledgeItemIdDelete>>,
    { itemId: string }
  > = (props) => {
    const { itemId } = props ?? {};

    return deleteKnowledgeItemApiKnowledgeItemIdDelete(itemId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteKnowledgeItemApiKnowledgeItemIdDeleteMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof deleteKnowledgeItemApiKnowledgeItemIdDelete>>
  >;

export type DeleteKnowledgeItemApiKnowledgeItemIdDeleteMutationError =
  ErrorType<HTTPValidationError>;

/**
 * @summary Delete Knowledge Item
 */
export const useDeleteKnowledgeItemApiKnowledgeItemIdDelete = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteKnowledgeItemApiKnowledgeItemIdDelete>>,
      TError,
      { itemId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteKnowledgeItemApiKnowledgeItemIdDelete>>,
  TError,
  { itemId: string },
  TContext
> => {
  const mutationOptions =
    getDeleteKnowledgeItemApiKnowledgeItemIdDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Search knowledge items using text matching.

TODO: Integrate with ChromaDB for vector similarity search.
Current implementation uses simple text matching.
 * @summary Search Knowledge
 */
export const searchKnowledgeApiKnowledgeSearchPost = (
  params: SearchKnowledgeApiKnowledgeSearchPostParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<KnowledgeSearchResult[]>(
    { url: `/api/knowledge/search`, method: "POST", params, signal },
    options,
  );
};

export const getSearchKnowledgeApiKnowledgeSearchPostMutationOptions = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof searchKnowledgeApiKnowledgeSearchPost>>,
    TError,
    { params: SearchKnowledgeApiKnowledgeSearchPostParams },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof searchKnowledgeApiKnowledgeSearchPost>>,
  TError,
  { params: SearchKnowledgeApiKnowledgeSearchPostParams },
  TContext
> => {
  const mutationKey = ["searchKnowledgeApiKnowledgeSearchPost"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof searchKnowledgeApiKnowledgeSearchPost>>,
    { params: SearchKnowledgeApiKnowledgeSearchPostParams }
  > = (props) => {
    const { params } = props ?? {};

    return searchKnowledgeApiKnowledgeSearchPost(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SearchKnowledgeApiKnowledgeSearchPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof searchKnowledgeApiKnowledgeSearchPost>>
>;

export type SearchKnowledgeApiKnowledgeSearchPostMutationError =
  ErrorType<HTTPValidationError>;

/**
 * @summary Search Knowledge
 */
export const useSearchKnowledgeApiKnowledgeSearchPost = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof searchKnowledgeApiKnowledgeSearchPost>>,
      TError,
      { params: SearchKnowledgeApiKnowledgeSearchPostParams },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof searchKnowledgeApiKnowledgeSearchPost>>,
  TError,
  { params: SearchKnowledgeApiKnowledgeSearchPostParams },
  TContext
> => {
  const mutationOptions =
    getSearchKnowledgeApiKnowledgeSearchPostMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
